### ISSUE TITLE
`printf` directive executor assumes C strings are UTF-8 encoded.  Should we revisit this assumption?

### ISSUE THREAD

**Issue by bboston7** [GaloisInc/crucible#1010]
[`Lang.Crucible.LLVM.Printf.executeDirectives` treats string directives as UTF-8 encoded](https://github.com/GaloisInc/crucible/blob/8ab240b1e45aae393d8685a5a914c6f611857b57/crucible-llvm/src/Lang/Crucible/LLVM/Printf.hs#L354).  I imagine this is fine in most programs that do reasonable things with strings, but if we wish to faithfully model the `printf` family of functions in cases where a program passes binary data to `printf` with a `%s` format specifier, then `executeDirectives` will likely mangle the string by misinterpreting it as a UTF-8 string rather than a sequence of bytes.  This issue came up in the Ambient project where we were trying to use `executeDirectives` to model malicious use of a `sprintf` call with a `%s` format specifier to copy binary data.  In this case, the UTF-8 interpretation mangles the binary data leading to an incorrect model of `sprintf`.

The question I'd like to pose for discussion is: Should we try to more faithfully model the `%s` format specifier in `executeDirectives`?  Or are we OK with assuming C strings are UTF-8 strings?

**Comment by robdockins** [comment]
When I built the printf capabilities, it was basically just to get a reasonable approximation of user output.  If you actually care about the precise formatting results and such... I guess it makes sense to get it right. Doing so with symbolic values will be... exciting, but maybe you're not interested in that.

As far as I can tell, `printf` doesn't pay attention to locale settings or anything, and I think "string" in the C standard pretty much always refers to a sequence of bytes, so "%s" should probably handle sequences of 8-bit chars, and as I read it "%sl" indicates wide characters (16-bit chars).

**Comment by RyanGlScott** [comment]
> As far as I can tell, `printf` doesn't pay attention to locale settings or anything

Sadly, this is not quite true, as there are some parts of `printf` that are locale-dependent. For example, the `man` page for `printf` has this to say:

       For some numeric conversions a radix character ("decimal point") or thousands' grouping character is used.  The actual
       character used depends on the LC_NUMERIC part of the locale.  (See setlocale(3).)  The POSIX locale uses '.' as  radix
       character, and does not have a grouping character.  Thus,

               printf("%'.2f", 1234567.89);

       results  in  "1234567.89" in the POSIX locale, in "1234567,89" in the nl_NL locale, and in "1.234.567,89" in the da_DK
       locale.

Luckily, I don't think the locale affects the way the text is encoded, which is the root of the issue above.

> and I think "string" in the C standard pretty much always refers to a sequence of bytes

Indeed, this seems like a safe bet. This is probably not a safe bet if you want to model the behavior of `wprintf`, but that's a separate matter.

> as I read it "%sl" indicates wide characters (16-bit chars).

Do you mean `%ls` here?

**Comment by robdockins** [comment]
Yes, I meant `%ls`.
