### ISSUE TITLE
crux-mir supported toolchain version too old

### ISSUE THREAD

**Issue by podhrmic** [GaloisInc/crucible#1059]
Hi! I wanted to take crux-mir for a spin, and try some tests on [smoltcp](https://github.com/smoltcp-rs/smoltcp) library.

However, the crux-mir supported toolchain (`nightly-2020-03-22-x86_64-unknown-linux-gnu`) doesn't work for my library (`cargo build` will fail). I tried rewinding to older smoltcp releases, to no avail.

Looks like the offender is [mir-json](https://github.com/GaloisInc/mir-json#installation-instructions) - what does it take to support at least a slightly newer toolchain than 2020?

**Comment by RyanGlScott** [comment]
It's a little bit of both. `mir-json` will need to be overhauled, and the resulting JSON schema will also need to be adapted to on the `crux-mir` side. This is something that we are actively working on.

**Comment by RyanGlScott** [comment]
This was fixed in #1096.
