### ISSUE TITLE
LLVM devs insist on changing the types of their intrinsics

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/crucible#108]
Different versions of LLVM have been adding/removing arguments from a variety of compiler intrinsics.  
Currently, we will simply error out during translation if the type `crucible-llvm` assigns to an intrinsic doesn't match the declaration produced by the compiler.

As a result, we have implicit couplings with specific, but undocumented versions of clang.

Somehow, we need to manage this source of coupling, either by having a more flexible way of installing intrinsics, or by reflecting on the compiler version to determine which version of intrinsics to install.

**Comment by brianhuffman** [comment]
I came across another example of this problem. In recent LLVM versions, the `llvm.objectsize` instrinsic has had another boolean argument added to it: https://reviews.llvm.org/D28494

**Comment by robdockins** [comment]
The `llvm.memcpy.*` family of intrinsics have changed type relatively recently.  They no longer have an argument that specifies alignment constraints, but instead the source and destination pointers may have the `align` argument attribute.

As a result, we need to add an additional override template for the new type signatures of `memcpy`.
