### ISSUE TITLE
llvm: Check if call stack is empty

### ISSUE THREAD

**Issue by langston-barrett** [GaloisInc/crucible#1112]
For the sake of pretty-printing, it would be helpful to be able to check if a [`CallStack`](https://github.com/GaloisInc/crucible/blob/3bdafe4fe1ed03e49a4255082cfe4d2e4a524f4b/crucible-llvm/src/Lang/Crucible/LLVM/MemModel/CallStack.hs) is empty.

**Comment by RyanGlScott** [comment]
I agree. While we're at it, we might consider just exporting the `CallStack` constructor somewhere (even if it's just in an internal module). That would allow downstream clients to write functions like the one requested here without having to first change `crucible-llvm`.
