### ISSUE TITLE
Adapt `crucible-llvm` to more `llvm-pretty` functions requiring implicit `?config` parameters

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/crucible#1145]
When we next bump the `llvm-pretty` submodule, we will likely need to bring in the changes from https://github.com/elliottt/llvm-pretty/pull/118 and friends. Among other changes, these PRs add implicit `?config :: Config` constraints to functions that did not have them before, such as `ppType`. This means that `crucible-llvm` will fail to compile if we don't make any other changes:

```
[22 of 53] Compiling Lang.Crucible.LLVM.Errors.MemoryError ( src/Lang/Crucible/LLVM/Errors/MemoryError.hs, interpreted )

src/Lang/Crucible/LLVM/Errors/MemoryError.hs:160:73: error:
    • Could not deduce: ?config::L.Config
        arising from a use of ‘L.ppType’
      from the context: IsExpr (SymExpr sym)
        bound by the type signature for:
                   ppMemoryOp :: forall sym (w :: GHC.TypeNats.Nat) ann.
                                 IsExpr (SymExpr sym) =>
                                 MemoryOp sym w -> Doc ann
        at src/Lang/Crucible/LLVM/Errors/MemoryError.hs:122:1-63
    • In the first argument of ‘viaShow’, namely ‘(L.ppType sig)’
      In the second argument of ‘(<+>)’, namely ‘viaShow (L.ppType sig)’
      In the expression:
        "Attempting to load callable function with type:"
          <+> viaShow (L.ppType sig)
    |
160 |   vsep [ "Attempting to load callable function with type:" <+> viaShow (L.ppType sig)
    |                                                                         ^^^^^^^^
```

This is only one example of the breakage—there are others that lie in wait after this one.

Note that we are mainly using the `llvm-pretty` printer in `crucible-llvm` for the sake of defining `Show` instances and creating error messages, not for creating machine-readable LLVM code. As a result, I think it would suffice to wrap each of these functions in a `ppLLVM` function that uses the `Config` corresponding to the most recent LLVM version that `llvm-pretty` supports.

**Comment by kquick** [comment]
> As a result, I think it would suffice to wrap each of these functions in a ppLLVM function that uses the Config corresponding to the most recent LLVM version that llvm-pretty supports.

There is a default value that can be used in this case, as introduced here: https://github.com/elliottt/llvm-pretty/pull/119/files#diff-0f3f6a9dbd801659caff963256924e5e6eb5326a6bce6dbede8482aa205a09d5R70-R74
