### ISSUE TITLE
crucible-syntax: Remove `ACFG`

### ISSUE THREAD

**Issue by langston-barrett** [GaloisInc/crucible#1149]
This type is redundant:

https://github.com/GaloisInc/crucible/blob/a8839cda3f1570ff921237ce48606a006cd26e0a/crucible-syntax/src/Lang/Crucible/Syntax/Concrete.hs#L1928-L1933

It stores types for the arguments and return value of the underlying CFG, but these are available via the CFG's handle.

**Comment by RyanGlScott** [comment]
Ugh, good catch. Sadly, this is a somewhat common pattern in the `crucible-syntax`. I did my best to expunge things of this sort in #1053, but this slipped through the cracks.

**Comment by RyanGlScott** [comment]
But come to think of it, `ACFG` also existentially closes over the `init` and `ret` type variables, so perhaps it is still serving a useful purpose in that regard. Or is there another data type that already does this? (`SomeCFG` existentially closes over `s` only, so it wouldn't do.)

**Comment by RyanGlScott** [comment]
Ah, this exists today as `AnyCFG`:

https://github.com/GaloisInc/crucible/blob/a8839cda3f1570ff921237ce48606a006cd26e0a/crucible/src/Lang/Crucible/CFG/Core.hs#L827-L829

At least, it's very close—it doesn't existentially close over an `IsSyntaxExtension ext` constraint. But it's unclear to me if that is actually necessary.
