### ISSUE TITLE
Loading from a field of a one-element struct fails with "Invalid memory load"

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/crucible#12]
Here's the C code:
```
struct single {
	int value;
};

int get (struct single *p) {
	return p->value;
}
```
Which compiles to the following LLVM:
```
%struct.single = type { i32 }

; Function Attrs: nounwind ssp uwtable
define i32 @get(%struct.single*) #0 {
  %2 = alloca %struct.single*, align 8
  store %struct.single* %0, %struct.single** %2, align 8
  %3 = load %struct.single*, %struct.single** %2, align 8
  %4 = getelementptr inbounds %struct.single, %struct.single* %3, i32 0, i32 0
  %5 = load i32, i32* %4, align 4
  ret i32 %5
}
```

I ran this with the following saw-script:
```
load_crucible_llvm_module "single.bc";
crucible_llvm_verify "get" []
  do {
    x <- crucible_fresh_var "x" i32;
    p <- crucible_alloc (llvm_struct "struct.single");
    crucible_points_to p (crucible_struct [crucible_term x]);
    crucible_execute_func [p];
    crucible_return (crucible_term x);
  }
  z3;
```
And here's the result:
```
Symbolic execution failed.
Invalid memory load: (1, 0x8:[64], 0x0:[64])
in get at internal
Stack frame
  Allocations:
    StackAlloc (2, 0x0:[64]) 0x8:[64]
  Writes:
    *(2, 0x0:[64]) := ptr(1, 0x0:[64])
Base memory
  Allocations:
    HeapAlloc (1, 0x0:[64]) 0x8:[64]
  Writes:
    *(1, 0x0:[64]) := {base+0 = c2:bv}
)
```

If I add a second field to the struct declaration, then it works just fine.

**Comment by atomb** [comment]
This is speculation, but I wonder if it's an issue of having loads and stores at different types. In some sense, a single-element struct type is isomorphic to the type of its single field, so it could be the case that we're initializing it as a struct (which the memory dump suggests) but then the generated LLVM code is optimized to treat it just as an `i32`, and the LLVM memory model doesn't recognize that `i32` and `{ i32 }` are basically the same thing.

**Comment by brianhuffman** [comment]
@robdockins suggested that the problem might be related to trailing padding. Indeed, if I change the type inside the struct to either `int64_t` or `int *` (both of which have 8-byte size and alignment, so no trailing struct padding), then the verification works.

**Comment by brianhuffman** [comment]
I have a theory about this: It might be due to us calculating struct alignments incorrectly (or at least in a way that doesn't match how Clang and LLVM actually do it).

Crucible calculates data alignments based on the description in the LLVM Language Reference (http://llvm.org/docs/LangRef.html#data-layout):

> When constructing the data layout for a given target, LLVM starts with a default set of specifications which are then (possibly) overridden by the specifications in the datalayout keyword. The default specifications are given in this list: [...]
> `a:0:64` - aggregates are 64-bit aligned

Accordingly, Crucible/LLVM gives all structs a minimum alignment (and thus a minimum size) of 8 bytes. However, the generated LLVM in my original post shows that the `load i32` has an alignment of 4 bytes. Also, `sizeof(struct single)` yields a value of 4 bytes. Clang/LLVM obviously are not following the language reference on this point, and so maybe we should get rid of the default-64-bit struct alignment in Crucible/LLVM.
