### ISSUE TITLE
Type mismatch when storing value.

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/crucible#122]
Maybe a duplicate of issue #84?  This is from the Dec 13 nightly saw-script:

    You have encountered a bug in Crucible's implementation.
    *** Please create an issue at https://github.com/GaloisInc/crucible/issues
    
    %< --------------------------------------------------- 
      Revision:  5fa44e23678c78fdb47491d8929ed464f604d82e
      Branch:    HEAD
      Location:  MemModel.packMemValue
      Message:   Type mismatch when storing value.
                 *** Expected storable type: bitvectorType 1
                 *** Given crucible type: RecursiveRepr LLVM_pointer [BVRepr 1]
    CallStack (from HasCallStack):
      panic, called at src/Lang/Crucible/Panic.hs:11:9 in crucible-0.4-2y2VTzHzrDE2LYq2Ylapqc:Lang.Crucible.Panic
      panic, called at src/Lang/Crucible/LLVM/MemModel.hs:526:3 in crucible-llvm-0.1-1P35wangloLKOrUaTKJ1w2:Lang.Crucible.LLVM.MemModel
    %< --------------------------------------------------- 

I do not have a small example to demonstrate this, but if need be I can try to whittle down from the files that are causing this.

**Comment by robdockins** [comment]
If you have a small or smallish example that exhibits this problem, that would be helpful.  It sure looks like #84, but I thought we had that one squashed...

**Comment by msaaltink** [comment]
I am unable to replicate this.  I think the original problem was me accidentally running an older version of SAW, thinking I was running the latest - I had been working on something else where I needed to compare versions and had different PATHs in different shells.  Classic user error!
