### ISSUE TITLE
Crucible references `check_sat` in several places

### ISSUE THREAD

**Issue by benjaminfjones** [GaloisInc/crucible#14]
There are several references to `check_sat` in the Crucible library which, afaik, is a function from another project.

In particular, this error message might be confusing to a Crucible user: 

https://github.com/GaloisInc/crucible/blob/master/crucible/src/Lang/Crucible/Solver/SimpleBackend/SMTLib2.hs#L469

**Comment by robdockins** [comment]
`check-sat` is also the name of the SMTLib2 command that directs the solver to perform sat checking.  I think the name is sufficiently descriptive to keep.
