### ISSUE TITLE
Multiple definitions of SomeCFG

### ISSUE THREAD

**Issue by langston-barrett** [GaloisInc/crucible#143]
There are two datatypes called `SomeCFG` that are frequently used in proximity with one another. This is confusing!
https://github.com/GaloisInc/crucible/blob/1c420c3b373ed203cbe794daae5f020157f1ee2c/crucible/src/Lang/Crucible/CFG/Core.hs#L788-L791
https://github.com/GaloisInc/crucible/blob/1c420c3b373ed203cbe794daae5f020157f1ee2c/crucible/src/Lang/Crucible/CFG/Reg.hs#L871-L875

**Comment by travitch** [comment]
For what it is worth, they correspond to two different definitions of `CFG` that are used in close proximity to one another (the registerized CFG and the SSA CFG).
