### ISSUE TITLE
Crucible type mismatch when unpacking LLVM value

### ISSUE THREAD

**Issue by msaaltink** [GaloisInc/crucible#147]
```
You have encountered a bug in Crucible's implementation.
*** Please create an issue at https://github.com/GaloisInc/crucible/issues

%< --------------------------------------------------- 
  Revision:  f37e851962c8801488d3a95b66b484482ab347e6
  Branch:    HEAD
  Location:  MemModel.unpackMemValue
  Message:   Crucible type mismatch when unpacking LLVM value
             *** Crucible type: RecursiveRepr LLVM_pointer [BVRepr 32]
             *** LLVM value: <int64>
CallStack (from HasCallStack):
  panic, called at src/Lang/Crucible/Panic.hs:11:9 in crucible-0.4-GwlVLwuoPl4F1FvAuHqrPn:Lang.Crucible.Panic
  panic, called at src/Lang/Crucible/LLVM/MemModel.hs:980:3 in crucible-llvm-0.2-KQ25Yjy0j2KCysvOfIK9XR:Lang.Crucible.LLVM.MemModel
  unpackMemValue, called at src/SAWScript/CrucibleOverride.hs:1183:22 in saw-script-0.2-DwYX9KbsxTwHRNYKg6JR1r:SAWScript.CrucibleOverride
%< --------------------------------------------------- 
```

That's from the 2018-12-30 nightly build of SAW.
I also get this in a recent build of SAW, revision a463326f3284a6c98ba38f9a701b0dcf5547b907.

A possible cause is that I mistakenly wrote

    ret <- crucible_fresh_var "return" (llvm_int 64);
    crucible_return (crucible_term {{ret}});

for a function that returns an i32.

**Comment by siddharthist** [comment]
@msaaltink Thanks for reporting! Could you upload the full SAWscript and bitcode that produced this?

**Comment by msaaltink** [comment]
I managed to boil it down to something simple.  `badreturn.c` is

    #include <stdint.h>

    uint32_t f() { return 0; }
    uint64_t g() { return f(); };

And the SAWScript:

    m <- llvm_load_module "badreturn.bc";

    let f_setup = do {
      crucible_execute_func [];
      r <- crucible_fresh_var "r" (llvm_int 64);
      crucible_return (crucible_term r);
      crucible_postcond {{ r == 0 }} ;
      };

    f_fact <- crucible_llvm_unsafe_assume_spec m "f" f_setup;

    let g_setup = do {
      crucible_execute_func [];
      crucible_return (crucible_term {{0:[64]}});
      };

    crucible_llvm_verify m "g" [f_fact] false g_setup z3;

So it is definitely a case of user error, but would be nice of SAW to catch the error when processing the unsafe_assume.  To be fair though, it does say "unsafe" right in the name.

**Comment by robdockins** [comment]
Indeed, we really should be catching this sort of thing earlier.

**Comment by robdockins** [comment]
I think this bug may have been fixed via https://github.com/GaloisInc/saw-script/pull/442, I'll verify when I get a chance.
