### ISSUE TITLE
Speed up override matching

### ISSUE THREAD

**Issue by siddharthist** [GaloisInc/crucible#155]
Currently, the crucible-llvm registers overrides for declarations with no corresponding definition, which generally occurs for C standard library functions like `strlen` or `memcpy`. The algorithm is basically: for each declaration in the module, search through a list of overrides and see if the name matches. This is O(_nm_) where _n_ is the number of declarations and _m_ is the number of overrides in the list.

This could (and should) be improved to O(_n_ + _m_*log(_m_)) by first making a `Map L.Symbol (LLVMOverride ...)` and looking the declarations up in the map.  

The relevant code: https://github.com/GaloisInc/crucible/blob/7a9786196e378e002e8f6da26e9408d7922cf70e/crucible-llvm/src/Lang/Crucible/LLVM/Intrinsics.hs#L105-L113

**Comment by robdockins** [comment]
Unfortunately, it isn't quite that simple, as some of the override selection requires to look at a prefix of the symbol rather than the whole thing.  We could use a search trie, I suppose, which has similar complexity advantages.

**Comment by siddharthist** [comment]
This might be a good choice: http://hackage.haskell.org/package/data-stringmap-1.0.1.1/docs/Data-StringMap.html

**Comment by robdockins** [comment]
Yeah, that might work.  I think we'd have to invert the algorithm, but it should be OK.

That is, put all the declared and defined LLVM symbols in the map... then walk though the overrides we want to install, do a lookup or prefix find, install any overrides that match.

**Comment by robdockins** [comment]
I think we should consider raising the priority of this ticket, as it actually seems to be causing problems in practice.  Loading even modestly-sized bitcode files (~5MB) causes significantly slowdown (~45seconds) that appears to be mostly spent in the override matching/installation phase.  Profiling indicates the name-demangling algorithm is occupying the bulk of program runtime, and demangling is only done during override installation.

A better algorithmic approach will probably go a long way, in addition to chasing down potential space-leaks in the underlying name demangling algorithm.

**Comment by robdockins** [comment]
PR #228 has significantly improved this situation, to the point that bitcode parsing is now the dominant factor for moderately-sized bitcode inputs.  There may still be room for more sophisticated pre-filtering algorithms (perhaps based on RE matching, for example), but further work on this should probably be delayed until and unless further scaling-up causes override matching to dominate startup time again.
