### ISSUE TITLE
Source language specific overrides (LLVM)

### ISSUE THREAD

**Issue by langston-barrett** [GaloisInc/crucible#158]
See also #155. One way to speed up override matching (though not asymptotically) would be to use some heuristics to try to determine the source language of an LLVM module, and then only install the appropriate intrinsics/overrides. 

For example, 
 - Every LLVM module needs the LLVM intrinsic overrides
 - Every C program needs the above plus the libc overrides
 - Every C++ program needs the above plus the libc++

**Comment by robdockins** [comment]
I think other changes we've made to override matching means this isn't an issue.
