### ISSUE TITLE
Simplify Crucible assumption management

### ISSUE THREAD

**Issue by atomb** [GaloisInc/crucible#16]
In adding path satisfiability checking to the SAWCore backend recently, @robdockins and I concluded that the path condition management done by the `sbAddAssumption`, `sbPushBranchPred`, `sbBacktrackToState`, and `sbSwitchToState` functions in the `IsSimpleBuilderState` class might be more complex or fragile than necessary. Perhaps it should be refactored.

**Comment by atomb** [comment]
See db1cb8775db3cf8b6d38a70e641f85054a3f7789 for some changes that were needed to the `SimpleBackend` module and could easily be missed.

**Comment by robdockins** [comment]
As part of the recent Crucible/What4 refactoring, the handling of branch conditions was significantly refactored, and simplifies these issues significantly.
