### ISSUE TITLE
`sawRegisterSymFunInterp` has a surprising and undocumented argument convention

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/crucible#167]
Here is the declaration of `sawRegisterSymFunInterp` from https://github.com/GaloisInc/crucible/blob/master/crucible-saw/src/Lang/Crucible/Backend/SAWCore.hs#L229:
```
-- | Register an interpretation for a symbolic function.
-- This is not used during simulation, but rather, when we translate
-- crucible values back into SAW.
sawRegisterSymFunInterp ::
  SAWCoreBackend n fs ->
  B.ExprSymFn n args ret ->
  (SC.SharedContext -> [SC.Term] -> IO SC.Term) ->
  IO ()
```
To the given symbolic function, it associates a function (of type `SharedContext -> [Term] -> IO Term`) for building a saw-core term from a list of arguments. But what's not explained in the documentation is that it expects the list to be in *reverse order*.

Nowhere in the saw codebase do we ever deal with reversed argument lists. For this reason I propose to swap the convention in `sawRegisterSymFunInterp` to use the regular (forward) argument ordering instead.

This is potentially a breaking change, but given that the reverse-order behavior is both unusual and undocumented, it's likely that every current user of `sawRegisterSymFunInterp` is using it wrong.

**Comment by robdockins** [comment]
Oy... do you get the impression that this is deliberate, or is it due to some foldl/foldr mixup somewhere?

**Comment by brianhuffman** [comment]
The helper function `evalAsgn` (https://github.com/GaloisInc/crucible/blob/master/crucible-saw/src/Lang/Crucible/Backend/SAWCore.hs#L663) is where the reversed-list convention is established. It converts an `Assignment` to a list of terms, and I think that producing a reversed list was just the easiest way to write it.
