### ISSUE TITLE
Crucible AST representation for What4 uninterpreted functions

### ISSUE THREAD

**Issue by travitch** [GaloisInc/crucible#186]
There is currently no way to represent what4 uninterpreted functions (or defined functions) in the Crucible AST.

I recently worked around this by adding a syntax extension to let me create my uninterpreted functions (as `SymExpr`s) when necessary, but being able to directly form them in Crucible would be convenient.

**Comment by kquick** [comment]
Might be obsoleted if crucible-server is removed.

**Comment by travitch** [comment]
Redirect to #189
