### ISSUE TITLE
Symbolic simulation of branching code in crucible-jvm is very slow

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/crucible#193]
In the old jss-based saw-script verification of ecdsa, the `leq` method is verified in a fraction of a second. However, in the crucible-jvm version, the symbolic simulation alone takes nearly 20 seconds. (The verification uses arrays of length 12.)
```
  static boolean leq(int[] x, int[] y) {
    int i = x.length;
    do {
      --i;
      if (x[i] != y[i]) {
        boolean xPos = 0 <= x[i];
        boolean yPos = 0 <= y[i];
        if (!yPos && xPos) return true;
        if (!xPos && yPos) return false;
        return x[i] < y[i];
      }
    } while (i != 0);
    return true;
  }
```
Profiling shows that most of the time and allocation is spent in the `globalMuxFn.muxEntry` function from `Lang.Crucible.Simulator.GlobalState` and functions called by it. In particular, functions `muxVariant` and `muxStruct` from `Lang.Crucible.Simulator.RegValue` are each called several hundred thousand times.

I tried copying this method definition to make a minimal example, but by itself it runs much more quickly (a few tenths of a second). In the ecdsa proof, lots of java classes have been pre-loaded before this method is executed, and so it appears that having a large number of objects already loaded into crucible references is what makes the muxing so slow.

To fix this, we need to reimplement muxing of the global state so that it doesn't need to traverse the entire contents of memory every time. Perhaps we could track which references may have been touched since the last branch, and only mux the contents of those references. Or we could represent crucible global state using an explicit history like the llvm memory model does.

**Comment by robdockins** [comment]
@brianhuffman, would you say this issue is fixed now, at least from the crucible side?

**Comment by brianhuffman** [comment]
Yeah, I think we can go ahead and close this now.
