### ISSUE TITLE
Consider an enumeration type for solvers

### ISSUE THREAD

**Issue by siddharthist** [GaloisInc/crucible#194]
In the `SolverAdapter` type, we allow for a `String` name field. Since the solvers we support in What4 are fixed and known at compile time, we should probably make this an enumeration type to support easier programatic inspection.

**Comment by travitch** [comment]
Is what4-abc a counterexample to that? It is defined outside of what4 core, and provides a solver implementation.

**Comment by robdockins** [comment]
Indeed, the entire `SolverAdapter` structure is designed to allow later packages to provide implementations that the `crucible` base package doesn't know about.

**Comment by siddharthist** [comment]
Ah, thanks for correcting me. Good to know!
