### ISSUE TITLE
Update GHC versions in Travis

### ISSUE THREAD

**Issue by langston-barrett** [GaloisInc/crucible#225]
We should test with the latest patch releases of GHC. We currently test 8.6.3 and 8.4.3, we should test 8.6.5 and 8.4.4. All of these are available in [the hvr/ghc ppa](https://launchpad.net/%7Ehvr/+archive/ubuntu/ghc/+index?batch=75&memo=75&start=75).

It would also be nice to add a job for GHC 8.8.1 alpha (with allowed failure) to see what breaks.

**Comment by robdockins** [comment]
This is subsumed by github actions.
