### ISSUE TITLE
Bitcode parsing dominates runtime

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/crucible#227]
Some recent test cases using `crux-llvm` have indicated that, for moderately-sized bitcode files, bitcode parsing dominates the runtime, and has significantly worse-than-linear performance.

For example, smallish C++ bitcode file (containing little more than the C++ standard library) generates a 5.5Mb file.  Based on some rough metrics, bitcode parsing seems to occupy about 80% of the runtime for (26 seconds out of 32) for a simple verification task.

A more realistic example that contains the entire library under consideration produces a file that is about 28Mb.  In this case, more than 10 minutes elapsed before I killed the program, as it appeared to be thrashing in swap before ever beginning the verification task.

Some profiling/space-leak hunting/etc seems to be in order.

**Comment by brianhuffman** [comment]
The pull requests GaloisInc/llvm-pretty-bc-parser#130 and elliottt/llvm-pretty#64 reduce a lot of the wasteful memory usage of bitcode parsing. Performance is still not great, however further improvements will require more serious algorithmic changes.

**Comment by robdockins** [comment]
The low-hanging fruit have been picked here.  To significantly improve performance, we will need to fix https://github.com/GaloisInc/llvm-pretty-bc-parser/issues/133, I think.
