### ISSUE TITLE
LLVM and pointer arithmetic

### ISSUE THREAD

**Issue by lcasburn** [GaloisInc/crucible#31]
Could the LLVM memory model be updated to allow pointer arithmetic?

Here's an example C program that computes and returns the length of a string, but produces an error within the `crucible-llvm` library.
```c
#include <stdio.h>
#include <stdint.h>

uint64_t mystrln(uint8_t *str) {
  uint8_t *s;
  for (s = str; *s != 0; ++s)
    ;
  return (s - str);
}

int main() {
  uint8_t foo[7] = {'f','o','o','b','a','r',0};
  printf("length of '%s' is %llu\n", foo, mystrln(foo));
  return 0;
}
```

The LLVM translation reports an error on line 8, indicating there is a
```
type mismatch when assigning register r11 , BVRepr 64 , RecursiveRepr LLVM_pointer") % 8:11
```

The LLVM output associated line 8 from the above c program converts the pointers `s` and `str` to integers before doing the subtraction.
```llvm
; <label>:5                                       ; preds = %1
  %s.0.lcssa = phi i8* [ %s.0, %1 ]
  %6 = ptrtoint i8* %s.0.lcssa to i64, !dbg !43
  %7 = ptrtoint i8* %str to i64, !dbg !43
  %8 = sub i64 %6, %7, !dbg !43
  ret i64 %8, !dbg !44
}
```

**Comment by TomMD** [comment]
If we need more examples that break then I suggest looking at musl which has significant low level optimizations that surface as pointer issues.  For example:

```
#include <string.h>
#include <stdint.h>
#include <limits.h>

#define ALIGN (sizeof(size_t))
#define ONES ((size_t)-1/UCHAR_MAX)
#define HIGHS (ONES * (UCHAR_MAX/2+1))
#define HASZERO(x) ((x)-ONES & ~(x) & HIGHS)

size_t strlen(const char *s)
{
  const char *a = s;
  const size_t *w;
  for (; (uintptr_t)s % ALIGN; s++) if (!*s) return s-a;
  for (w = (const void *)s; !HASZERO(*w); w++);
  for (s = (const void *)w; *s; s++);
  return s-a;
}
```

**Comment by robdockins** [comment]
Regarding the original reported bug, I'm reasonably confident this will be fixed by improving the translation-time representation of pointers.  Essentially the idea is to treat pointers and pointer-width integer types the same way at translation time, and defer the is-it-a-pointer-or-an-integer question to simulation time.

As for the idioms in the code @tommd posted.... wow, that's some pretty nasty bit-level hacking.  I'm pretty confident that idiom is not standards-compliant C.  It's going to be very difficult to support that.

**Comment by robdockins** [comment]
The original example in this bug is now working correctly.

The `strlen` posed by @TomMD is indeed going quite a bit beyond the types of pointer arithmetic allowed by our memory model.  What it would take to support this example is a larger discussion than this issue.
