### ISSUE TITLE
Calling functions that take void * parameters?

### ISSUE THREAD

**Issue by WeeknightMVP** [GaloisInc/crucible#33]
I'm trying to verify code that passes arrays of various types (e.g. `unsigned int` or `typedef struct Foo { unsigned int[32] } Foo_t`) to assembly subroutines that take `void *` parameters (e.g. `memcpy`, `memset`), but I'm not quite sure how to specify these subroutines and their compatibility with the callers.  So far, I've tried the following mockup:

```C
// voidTest.c

/** mockup of subroutine to assume/override */
void clear_void(void *arr, unsigned int size) {
    unsigned char *cArr = arr;
    for (int i = 0; i < size; i++) {
        cArr[i] = 0;
    }
}

/** mockup of caller that passes a pointer to an array of unsigned ints to the void *-based subroutine */
void clear_uints(unsigned int *uints, unsigned int numUInts) {
    clear_void(uints, numUInts * sizeof(unsigned int));
}
```

```Haskell
// saw -d 4 voidTest.saw

/** 
 * spec for mockup of subroutine that clears the given number of bytes from the 
 * arbitrary array pointed to by a given void * 
 */
let clear_void_spec : CrucibleSetup() = do {
    let voidArrayType = (llvm_array 12 (llvm_int 8));
    
    arr <- (crucible_fresh_var "arr" voidArrayType);
    p_arr <- (crucible_alloc voidArrayType);
    let v_arr = (crucible_term arr);
    
    size <- (crucible_fresh_var "size" (llvm_int 32));
    let v_size = (crucible_term size); 
    
    crucible_equal v_size (crucible_term {{ 12:[32] }});
    crucible_points_to p_arr v_arr;
    
    crucible_execute_func [p_arr, v_size];
    
    crucible_points_to p_arr (crucible_term {{ zero:[12][8] }});
};

/** 
 * spec for function that calls the subroutine to clear the given number of 
 * unsigned ints from the array pointed to by a specified unsigned int * 
 */ 
let clear_uints_spec : CrucibleSetup() = do {
    let uintsType = (llvm_array 3 (llvm_int 32));
    
    uints <- (crucible_fresh_var "uints" uintsType);
    p_uints <- (crucible_alloc uintsType);
    let v_uints = (crucible_term uints);
    
    numUInts <- (crucible_fresh_var "numUInts" (llvm_int 32));
    let v_numUInts = (crucible_term numUInts); 
    
    crucible_equal v_numUInts (crucible_term {{ 3:[32] }});
    crucible_points_to p_uints v_uints;
    
    crucible_execute_func [p_uints, v_numUInts];
    
    crucible_points_to p_uints (crucible_term {{ zero:[3][32] }});
};

let main : TopLevel () = do {
    voidTest <- llvm_load_module "voidTest.bc";
    
    // The actual subroutine result would be "crucible_llvm_unsafe_assume_spec ..."
    clear_void_12_result <- crucible_llvm_verify voidTest "clear_void" [] false clear_void_spec z3;
    clear_uints_3_result <- crucible_llvm_verify voidTest "clear_uints" [clear_void_12_result] false clear_uints_spec z3;
    
    print "Done!";
};
```

The code compiles in Clang/LLVM, but SAW reports an "invalid memory store"...

>   \> saw voidTest.saw
>   Loading file "...voidTest.saw"
>   Invalid memory store in clear_void at ..\src\voidTest.c:11:17
>   When calling llvm_store
>   In clear_void at ..\src\voidTest.c:11:17
>   Symbolic simulation failed along some paths!
>   Subgoal failed: @clear_void safety assertion: literal equality postcondition
>   SolverStats {solverStatsSolvers = fromList ["SBV->Z3"], solverStatsGoalSize = 140}
>   ----------Counterexample----------
>   ("arr",[255,0,0,0,0,0,0,0,0,0,0,0])
>   ("size",12)
>   user error ("crucible_llvm_verify" (...voidTest.saw:51:7):
>   Proof failed.)

...probably because I'm not correctly specifying this.  If Crucible/LLVM supports it, can you please provide an example to verify a caller that passes a pointer to an array of known type/length to a function that takes a `void *` and corresponding bytelength?  Thank you.

**Comment by robdockins** [comment]
This example is just nearly working.  The problem is that the following sequence sets up a situation that is hard for the symbolic simulator to handle:
```
    size <- (crucible_fresh_var "size" (llvm_int 32));
    let v_size = (crucible_term size); 
    crucible_equal v_size (crucible_term {{ 12:[32] }});
```

The better way to handle this is to simply write:
```
    let v_size = crucible_term {{ 12:[32] }};
```

The first sequence of lines sets up a symbolic variable named "size" and then remembers, on the side, that this symbolic variable is equal to a particular constant.  When it goes to do symbolic simulation, it only remembers that "size" is symbolic, which means that the loop that clears the array runs off the end because it doesn't know when to stop.  This is why you get what is essentially an out of bounds error.

If you instead set size directly to be a known constant, the symbolic simulator knows the exact value to use; and the loop terminates reliably before running off the end of the array.

**Comment by atomb** [comment]
This seems to work for me now. Can you check that it does for you, too, @WeeknightMVP ? As the script stands above, there's a spurious `Invalid memory store` message, followed by `Proof succeeded!` because the invalid store occurred on a path it can later show was infeasible. If you change the `false` to `true` in each of the `crucible_llvm_verify` calls, to turn on path satisfiability checking, then it succeeds without misleading noise.

**Comment by WeeknightMVP** [comment]
Before changing `crucible_llvm_verify` arguments from `false` to `true`:
```sh
$ saw voidTest.saw
Loading file "/home/ubuntu/workspace/example/issues/crucible/33/voidTest.saw"
Invalid memory store: address (3, 0xc:[64]) at type i8
in clear_void at internal
  In clear_void at internal
Symbolic simulation failed along some paths!
Proof succeeded! @clear_void
Registering override for `clear_void`
Proof succeeded! @clear_uints
Done!
```

After:

```sh
$ saw voidTest.saw
Loading file "/home/ubuntu/workspace/example/issues/crucible/33/voidTest.saw"
Proof succeeded! @clear_void
Registering override for `clear_void`
Proof succeeded! @clear_uints
Done!
```

Nice!  I agree with @robdockins that assigning directly to a constant is better, but am glad the symbolic simulator can now handle cases like this.

**Comment by robdockins** [comment]
It seems like this issue is resolved, feel free to reopen if there is more to discuss.
