### ISSUE TITLE
Pretty printer for CFG.Expr doesn't show predicate part of WithAssertion's partial value

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/crucible#341]
This is a follow-up to #337. Pull request #339 shows the `value` part of the `PartialValue` argument of `WithAssertion`, but it doesn't show the `AssertionTree`. @robdockins says we should print it:
https://github.com/GaloisInc/crucible/pull/339#issuecomment-553046607

Fixing this will require us to implement a pretty printer for the `AssertionTree` datatype in module `What4.Partial.AssertionTree`, and to update the `PrettyApp (App ext)` instance in module `Lang.Crucible.CFG` to call it.

**Comment by langston-barrett** [comment]
The printed trees are likely to be huge, they collect information about how that predicate was formed.

**Comment by brianhuffman** [comment]
On the #339 thread, @robdockins suggested that we at least indicate that some information has been omitted. Should we just do that, and forget about printing the `AssertionTree` then?

**Comment by brianhuffman** [comment]
I think we can consider #342 (which shows the omitted `AssertionTree` as `<some assertion>`) to be sufficient.
