### ISSUE TITLE
Call-stack reporting feature

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/crucible#348]
PR #295 and PR #292 are both related to adding call stack information to errors, and have been languishing for some time.  @kquick, @langston-barrett, what are your thoughts about the merits of these two approaches?  Does one subsume the other; are they actually orthogonal? Are they ready to merge?

**Comment by langston-barrett** [comment]
I'm not sure about their overlap, but mine is ready to merge whenever as long as we're fine with the mangled names.

**Comment by langston-barrett** [comment]
How is this related to https://github.com/GaloisInc/crucible/issues/424?

**Comment by langston-barrett** [comment]
Let's open more specific issues when we find particular error messages and exceptions that should include call stacks but currently don't.
