### ISSUE TITLE
Abstract domain evaluation for weighted sums of bitvectors is very slow

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/crucible#349]
My use case is verifying a C implementation of a popcount function over a large array of bytes with `saw`. This involves producing a very large number of terms of the form `if b then 1 else 0` and adding them all together.

On my example proof script, profiling shows that running `abstractEval` (from module `What4.Expr.Builder`) on weighted sums takes up more than 90% of the total runtime and allocation. Function `maxUnsigned` (from `Data.Parameterized.NatRepr`) takes up 22% of runtime and 25% of allocation all by itself.

We should reimplement the bitvector abstract domain to make this more efficient.

**Comment by robdockins** [comment]
I think this is mostly fixed now with the merge of #353 and #383.  However, I'd like to keep this bug open for now to track additional work to be done in this area.  There is still quadratic behavior arising from hash and abstract domain computations for the other map-like structures in what4.  These include the `BoolMap` and `SemiRingProduct` types, as well as the `ArrayMap` expression constructor.

**Comment by robdockins** [comment]
I believe this is now fixed with the merge of #387 and #390.
