### ISSUE TITLE
Create SV-COMP competition entry

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/crucible#351]
`crux` is nearly, but not quite, set up to be an SV-COMP competitor.  I think we could feasibly enter in the following SV-COMP categories: 1) ReachSafety, 2) MemSafety, 4) NoOverflows, 6) SoftwareSystems 8) C-Falsification, and maybe 9) Java-Overall (leaving out concurrency and termination).

To properly enter the competition, we'd need to do some additional work to parse the contest benchmark metadata files, produce counterexample witnesses in the expected format, and generally make sure we can run in the contest environment.

In addition, we should add the ability to check the `valid-memtrack` property, which states that memory should be freed before becoming inaccessible.

**Comment by robdockins** [comment]
CF #352

**Comment by RyanGlScott** [comment]
> In addition, we should add the ability to check the `valid-memtrack` property, which states that memory should be freed before becoming inaccessible.

I opened a separate issue (#790) for this part.

**Comment by RyanGlScott** [comment]
We have successfully whipped `crux-llvm` into competition shape, as chronicled [here](https://galois.com/blog/2022/01/crux-in-sv-comp-2022-a-retrospective/). I think this issue has served its purpose, so I'll close it in favor of the various other issues under the "SV-Comp" GitHub label.
