### ISSUE TITLE
Yices does not have necessary features enabled

### ISSUE THREAD

**Issue by chameco** [GaloisInc/crucible#379]
Since #372, some SAWScript regression tests using `w4_unint_yices` have been failing - see https://travis-ci.org/GaloisInc/saw-script/builds/625777088. It looks like the `useLinearArithmetic` feature flag is not being set. Previously, it was always enabled (along with the rest of `yicesDefaultFeatures`).

It would be easy to always enable the default features in addition to the requested features, but I'm unsure if this goes against the intent of #372.

ping @danmatichuk

**Comment by danmatichuk** [comment]
Merging the default option set with the requested one seems reasonable to me.

**Comment by robdockins** [comment]
OK, I just took a look at this: I think the underlying problem is actually this code from SMTWriter:

```
mkExpr t@(SemiRingLiteral (SR.SemiRingBVRepr _flv w) x _) = do
  checkLinearSupport t
  return $ SMTExpr (BVTypeMap w) $ bvTerm w x
```

This code is checking for linear arithmetic support, when actually it should be checking for bitvector theory support.
