### ISSUE TITLE
Crux hangs when generating reports for some inputs

### ISSUE THREAD

**Issue by atomb** [GaloisInc/crucible#407]
Some input files lead Crux (specifically `crux-llvm`, but maybe other languages) to hang when generating reports. For example, the following benchmark from SV-COMP:

https://github.com/sosy-lab/sv-benchmarks/blob/master/c/float-newlib/double_req_bl_0220a.c

The issue seems to occur during [`summarizeTree`,](https://github.com/GaloisInc/crucible/blob/master/crucible/src/Lang/Crucible/CFG/Extension/Safety.hs#L266) which has some known awkwardness and potential performance issues. In particular, changing [this line](https://github.com/GaloisInc/crucible/blob/master/crux/src/Crux/Report.hs#L128) from

````
goalReason = simErrorReasonMsg (simErrorReason conc)
````

to

````
goalReason = take 80 $ simErrorReasonMsg (simErrorReason conc)
````

seems to make the problem go away on all instances I've seen. However, it does that by leaving out part of the message and doesn't fundamentally fix the problem.

**Comment by robdockins** [comment]
Ah, I've seen this behavior where it hangs during report generation, but wasn't sure what caused it.

Yeah, we should probably address the underlying issue somehow, which roughly is that those error report trees can get very large... I hate to lose precision of the error messages, but when they get so large, I don't know that much can be usefully gleaned from them anyway.

**Comment by atomb** [comment]
Yeah, _very_ large is right. I've seen cases where this exhausts all available memory. And I've seen cases where it just spins at 100% CPU without allocating any new memory. It's not immediately clear how to fix it, honestly. One idea, though, is that we may essentially wind up with a tree of reasons that are all the same at the leaves but for some reason still exist as separate branches. And those trees, if they aren't simplified, can probably grow to sizes that are exponential in the number of branches in sequence that we encounter.

**Comment by robdockins** [comment]
Ah, indeed.  This is very possibly a loss of sharing problem.  The error trees might be built with sharing (which is perhaps why they don't bring things to their knees immediately), but as soon as we traverse them, we lose the sharing structure because it isn't explicit.

**Comment by robdockins** [comment]
OK, after taking a look at the code in `What4.Partial/AssertionTree`, I'm willing to bet that loss of sharing when doing traversals (via `cataMAT` or what-have-you) is at least part of the issue here.

**Comment by robdockins** [comment]
@atomb, what settings are you using on this verification? I'm having trouble exhibiting the behavior where it hangs during report generation.

**Comment by robdockins** [comment]
With the current state of things, this benchmark still takes a long time to build reports.  However, I think that's because it generated 96559 proof obligations during ~90sec of simulation time (of those, 6 came back with counterexamples).  As I write this comment, the process has written 1.5GB of JSON. However, it's doing so without growing its memory footprint, so I think we can declare this a success.

We probably should have an option for only generating reports for failing goals, however.

**Comment by atomb** [comment]
Yeah, I agree that that's a separate issue. The `proof-goals-fail-fast` option will probably already help, but something to log only failures could be useful. I'll create an issue.
