### ISSUE TITLE
`reduceApp` not doing enough simplification

### ISSUE THREAD

**Issue by benjaminselfridge** [GaloisInc/crucible#415]
In `What4.Expr.Builder`, the `reduceApp` function needs to perform a fold over semiring products/sums, and any other cases that involve n-ary lists of terms, to account for such terms having been simplified via substitution.

**Comment by robdockins** [comment]
For additional context, see:
https://github.com/GaloisInc/crucible/blob/b0d21e3775fb34a31e1a8485c2b850fe3852f804/what4/src/What4/Expr/Builder.hs#L3133

In particular, the cases such as:
```
    ConjPred xs -> conjPred sym xs

    SemiRingSum s -> semiRingSum sym s
    SemiRingProd pd -> semiRingProd sym pd
```

The problem is that `semiRingSum`, `conjPred`, etc. already assume that none of the subcomponents are literals, and therefore cannot be reduced any further.  We instead need to reduce these to the corresponding binary operations like `andPred` and `realAdd`, etc. to ensure that we apply all the relevant rewriting and reduction rules.

**Comment by benjaminselfridge** [comment]
I'm actually having trouble recreating this bug on a simple example -- I first noticed it on an out-of-date version of what4, and when I updated to master, the term got full reduced, which surprises me slightly.

**Comment by robdockins** [comment]
Do you have a minimized example?  We could try to bisect it and figure out what's going on.

Either way, seems like we should fix this.

**Comment by benjaminselfridge** [comment]
Here is the version that used to remain unreduced, but now reduces fully:

```
import Data.Parameterized.NatRepr
import Data.Parameterized.Some

import qualified Data.Parameterized.Context as PC
import qualified Data.Parameterized.Nonce as PN
import qualified What4.Expr.Builder as WB
import qualified What4.Interface as WI

data BuilderState t = BuilderState

main = do
  Some nonceGen <- PN.newIONonceGenerator
  sym <- WB.newExprBuilder WB.FloatUninterpretedRepr BuilderState nonceGen

  let width = knownNat @32
  let bvType = WI.BaseBVRepr width

  bv1Var <- WI.freshBoundVar sym (WI.safeSymbol "bv1") bvType
  bv2Var <- WI.freshBoundVar sym (WI.safeSymbol "bv2") bvType

  let bv1 = WI.varExpr sym bv1Var
  let bv2 = WI.varExpr sym bv2Var

  let argVars = PC.empty PC.:> bv1Var PC.:> bv2Var
  andExpr <- WI.bvAndBits sym bv1 bv2
  body <- WI.bvConcat sym andExpr andExpr
  f <- WI.definedFn sym (WI.safeSymbol "f") argVars body (const True)

  arg1 <- WI.bvLit sym width 0x1
  arg2 <- WI.bvLit sym width 0x0
  let args = PC.empty PC.:> arg1 PC.:> arg2
  res <- WI.applySymFn sym f args

  print body
  print res
```

Like I said, I'm having trouble coming up with an example that does not become fully reduced... I'm not sure what changed, though, between the head of master and whatever commit I was on.

**Comment by robdockins** [comment]
My hypothesis is that recent improvements to the bitvector abstract domain are the cause of the change.

**Comment by robdockins** [comment]
Indeed, bisection indicates that the first commit where your example program reduces to a constant is: fd635f1fe5789bdf464055b89cbc22ca89b849ec, which enables abstract domain computation for bitwise operations.
