### ISSUE TITLE
Separate solvers for pathsat checking and goal discharge

### ISSUE THREAD

**Issue by travitch** [GaloisInc/crucible#419]
I have a crux frontend where I'd like to use separate solvers for path satisfiability checking and actual goal checking. In particular, I want to do some experiments with dReal, which does not have support for online solving.

@atomb and others, would you be open to a crux option that lets you select a different solver for path satisfiability checking? I imagine that the default could stay the same (if you specify a solver with the current option, it is used for both), but that this change would add an extra option like `--online-solver` or `--path-sat-solver`.

**Comment by atomb** [comment]
Yes, this is something I've considered several times, too, and just haven't got around to implementing. Go for it!

**Comment by robdockins** [comment]
Agreed, it definitely something that makes sense.

**Comment by travitch** [comment]
Closed by #428
