### ISSUE TITLE
The TestEquality instance for LLVMPointer is suspicious

### ISSUE THREAD

**Issue by travitch** [GaloisInc/crucible#458]
The `TestEquality` instance for `LLVMPointer` returns true if the inputs are the same width, with no additional checks: https://github.com/GaloisInc/crucible/blob/3db599ec92e4f5b68b8570c25c38076228daa87b/crucible-llvm/src/Lang/Crucible/LLVM/MemModel/Pointer.hs#L129

This seems unsafe and uses of this instance should probably just be testing the width reprs explicitly.

**Comment by robdockins** [comment]
Agreed.  The contract for `TestEquality` is ambiguous at best, but we're pretty uniformly using it as a value equality check, and not just a type equality check.

**Comment by langston-barrett** [comment]
Here's the issue that appears to be tracking/discussing the ambiguity: https://github.com/GaloisInc/parameterized-utils/issues/63
