### ISSUE TITLE
Counterexample-driven error messages

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/crucible#462]
Once #453 is merged, we will have support for internally-annotated goals and assumptions.  Those that arise from the memory model, in particular, can be very complicated.  Instead of trying to print the entire goal and its annotations when a goal verification fails, it would be better instead to collapse the goal to just the relevant part according to the computed counterexample.  This ought to help users understand the goal better, as irrelevant or redundant parts can be omitted.

**Comment by atomb** [comment]
This is very cool! And @brianhuffman might want to think about this for some of the work he's planning.

**Comment by robdockins** [comment]
Implemented in #511
