### ISSUE TITLE
Check for overflow when shifting signed things

### ISSUE THREAD

**Issue by yav** [GaloisInc/crucible#49]
If we have an expressions like `x << y`, and `x` is at a signed type (or promoted to one!) we need to check that we don't overflow into the signed bit (i.e., it doesn't get set after the shift).

**Comment by robdockins** [comment]
As far as I can tell, we're doing the correct check here in the event that LLVM emits a `lsh` with the `nsw` flag.  Unfortunately, it isn't always emitting the flag, even when it would be justified by the source language.  As a result, we can't really handle this case unless clang gets more pedantic about the flags it emits.
