### ISSUE TITLE
Wasted solver communication in crux

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/crucible#528]
If crux is run without path-sat checking enabled, the symbolic simulator may still configure itself to use an online backend.  Even though no sat queries are issued during simulation, it appears that on some programs the simulator spends significant time simply streaming parts of the problem to the solver and maintaining state.

If path satisfiability checking is not requested, we should skip all this work and instead just use the offline backend for simulation.  The goal checking phase should be able to independently select to do online or offline solving.

**Comment by robdockins** [comment]
We should check, but I believe this was fixed by #570

**Comment by atomb** [comment]
This may be related to #627, but we can use that issue for tracking anything remaining. The core work is done.
