### ISSUE TITLE
Crux report.js and source.js can differ in file absolute paths

### ISSUE THREAD

**Issue by Ptival** [GaloisInc/crucible#534]
Both report.js and source.js contain absolute paths for files, however, they don't necessarily generate the same paths.

source.js does it this way:
https://github.com/GaloisInc/crucible/blob/996db66ca35950439282fc5724278dc5490ecd55/crux/src/Crux/Report.hs#L59

while report.js does it this way:
https://github.com/GaloisInc/crucible/blob/996db66ca35950439282fc5724278dc5490ecd55/crux/src/Crux/UI/JS.hs#L21-L23

On an input like `./path/to/file.c`, source.js will generate `/absolute/path/to/file.c`, while report.js will generate `/absolute/./path/to/file.c`.
This is problematic because:
https://github.com/GaloisInc/crucible/blob/996db66ca35950439282fc5724278dc5490ecd55/crux/src/Crux/UI/IndexHtml.hs#L25-L28

expects the value of one to be a key in a dictionary made from the other one, which breaks the UI on such cases.

**Suggested options**

- The quick and ugly fix is to replace `makeAbsolute` with path concatenation in generating source.js.

- The less dangerous but more painful fix is to call `makeAbsolute` for generating report.js. This is painful because `fabsolute` was in a pure function `jsLoc`, called from a pure function `jsSideCond`, called from a pure function `renderSideConds`. All these would need become IO.

- Rely on some generated identifier instead?

**Comment by robdockins** [comment]
Good catch!  I wonder if this is the same cause as the problems I'm seeing in #517.

I'm inclined to push IO down into the code that generates `report.js`, I don't think it will be too bad.  I'll give that a try and see if it fixes the problems I'm seeing.
