### ISSUE TITLE
`cabal v2-install` fails with various errors

### ISSUE THREAD

**Issue by spernsteiner** [GaloisInc/crucible#552]
`cabal v2-install` begins by running `cabal v2-sdist` on each package `cabal.project`, regardless of what target is being installed.  Currently, this fails on three packages:

 * [ ] `cabal v2-sdist pkg:crucible-go` fails with `cabal: Main.hs doesn't exist`.  The test suite main file `tests/Main.hs` is not present in the repo.
 * [ ] `cabal v2-sdist pkg:crucible-server` fails with `cabal: Error: Could not find module: Lang.Crucible.Proto with any suffix: ["gc","chs","hsc","x","y","ly","cpphs","hs","lhs","hsig","lhsig"]. If the module is autogenerated it should be added to 'autogen-modules'.`
 * [ ] `cabal v2-sdist pkg:crux-llvm` fails with `cabal: WinMain.hsMain.hs doesn't exist`.  Cabal appears to have concatenated two different conditional `main-is` directives into one.

Since the `sdist` step fails, nothing in the entire `crucible` repo can be installed using `cabal v2-install`.

I'm using `cabal-install version 3.0.0.0, compiled using version 3.0.1.0 of the Cabal library`

**Comment by atomb** [comment]
I would be in support of removing `crucible-server` from `cabal.project`, at least for the moment, which would fix the second one. The `crucible-go` issue should be easily fixable. The `crux-llvm` one, though, is really awkward (and seems clearly like a bug in Cabal).

**Comment by robdockins** [comment]
If we want to EOL crucible-server, I think that's a potentially reasonable step.  However, I think the suggested fix about would probably work for the immediate problem.  `Lang.Crucible.Proto` is a generated module.

**Comment by atomb** [comment]
Ah, yeah, if adding `Lang.Crucible.Proto` to `autogen-modules` will fix it, and it still builds, let's just do that.

**Comment by atomb** [comment]
I'm going to fix the `crux-llvm` part of this, and update the installation instructions to match.

**Comment by atomb** [comment]
See #555

**Comment by atomb** [comment]
Now #555 should entirely resolve this issue.
