### ISSUE TITLE
Crux-mir documentation appears incomplete - example does not run

### ISSUE THREAD

**Issue by TomMD** [GaloisInc/crucible#566]
N.B.

```
$ cargo --version
cargo 1.43.0
$ crux-mir --version
crux version: 0.1, crux-mir version: 0.1
$ cargo crux-test
error: no such subcommand: `crux-test`
```

But the documentation doesn't mention anything about dependencies on running this example

**Comment by ogham** [comment]
I'd like some more documentation too. Crucible looks great, but looking at the README, I'm not sure which commands are only appropriate for building it instead of running it (I'm trying to use the Docker container), and I can't see how to adapt the commands to run on my own code.

**Comment by atomb** [comment]
The packaging and documentation have been updated to resolve this issue. We now recommend users install `mir-json` in advance, using Cargo.
