### ISSUE TITLE
asMemAllocationArrayStore is fragile

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/crucible#571]
The following line, in particular, tests that an equality predicate reduces concretely to "True".  This test feeds into the structural matching code in SAW, and will reject override specifications if this test doesn't succeed.  In the process of modifying the SAW/Crucible interface code, I found a case where an "obvious" true equality wasn't passing this test because the terms involved were independently created.  This test starts passing if hash consing is turned on, which leads this syntactic test to succeed instead.

https://github.com/GaloisInc/crucible/blob/910c79158449c6fe96894203776ce24924006b14/crucible-llvm/src/Lang/Crucible/LLVM/MemModel/Generic.hs#L1554

We should find a more semantic way to perform these tests rather than relying on these fragile syntactic tests.

**Comment by kquick** [comment]
Is this something that concrete value tests like https://github.com/GaloisInc/what4/blob/master/what4/test/IteExprs.hs would have caught or been useful to validate?

**Comment by robdockins** [comment]
No, I don't think so.  The test isn't _wrong_, it's just too conservative.  Moreover, the behavior only emerges when the inputs are symbolic.

**Comment by robdockins** [comment]
Fixed via #572
