### ISSUE TITLE
Lazy errors for failed LLVM constant translations

### ISSUE THREAD

**Issue by atomb** [GaloisInc/crucible#58]
When translating LLVM instructions to Crucible, many failures result in Crucible code that will fail when executed, rather than failing during translation. This can be useful in the case where the untranslatable code is never actually executed. However, for translation of constants, the structure of the code doesn't make creation of error instructions straightforward. It would be nice to refactor it so that errors would only occur if untranslatable constants are actually used.

**Comment by robdockins** [comment]
I suppose we could just add a new `ErrorConstant` value, and cause it to raise an error during translation
(probably in `liftConstant`).  That would probably be sufficient also to correctly deal with the `inrange` constant GEP case from #57.

**Comment by robdockins** [comment]
Or, we could run `transConstExpr` in the `ExceptT` monad and call `reportError` on failure rather than calling `fail` in the generator monad.

**Comment by atomb** [comment]
I like the `ExceptT` approach. Then I think there's just one call site that would need to react to failure and generate code to raise an error:

https://github.com/GaloisInc/crucible/blob/master/crucible-llvm/src/Lang/Crucible/LLVM/Translation.hs#L560

**Comment by robdockins** [comment]
Yeah, that seems right.

**Comment by robdockins** [comment]
Do you have a small test case that exhibits the issue?  I could take a quick stab at doing this, should be pretty easy.
