### ISSUE TITLE
Path condition issue in crucible-c

### ISSUE THREAD

**Issue by andreistefanescu** [GaloisInc/crucible#59]
Crucible-C fails to verify the program below (as far as I can tell, it loses the path condition `a == 5`, although it still has `b >= 0`). 
```
extern int __VERIFIER_nondet_int(void);
extern void __VERIFIER_assert(int cond);

#include <assert.h>

int main()
{
  int a = __VERIFIER_nondet_int();
  int b = __VERIFIER_nondet_int();
  if (a == 5 && b >= 0) {
    __VERIFIER_assert(a == 5);
  }
  return 0;
}
```

**Comment by robdockins** [comment]
Bisecting this issue indicates that the problem first appears in e1884935, which introduced the new `GoalCollector` data structure for managing path conditions and proof obligations.

**Comment by yav** [comment]
OK, I'll have a look
