### ISSUE TITLE
out of the box commands for stack don't work: expects `cryptol-verifier` to exist

### ISSUE THREAD

**Issue by silky** [GaloisInc/crucible#605]
also, `saw-core`  has no package.yaml, so even if i just delete `cryptol-verifier` from the list of dependend-on packages i get:

```
12:07 PM noon φ crucible (master*) stack setup            
Stack looks for packages in the directories configured in
the 'packages' and 'extra-deps' fields defined in your stack.yaml
The current entry points to /home/noon/dev/ext/crucible/dependencies/saw-core/,
but no .cabal or package.yaml file could be found there.
```

**Comment by robdockins** [comment]
I don't think anyone working on this project is using stack anymore.  My personal inclination would be to delete the now-unmaintained `.yaml` files.  However, if stack support is useful to you, I'd be willing to accept patches to get them working again.

The present issue is that the `cryptol-verifier` repository (and several others) was merged into the `saw-core` repository recently.  It was renamed into the `cryptol-saw-core` package.  It would probably suffice to rename `dependencies/cryptol-verifier` into `dependencies/saw-core/cryptol-saw-core` and `dependencies/saw-core-what4` into `dependencies/saw-core/saw-core-what4`, etc.

**Comment by silky** [comment]
thanks @robdockins  for the response; no worries re: stack support just for me; if i do end up using this project a bit more i'll make the sacrifice and use cabal, if that's what is supported :)
