### ISSUE TITLE
Not all crux-llvm options appear in the README

### ISSUE THREAD

**Issue by langston-barrett** [GaloisInc/crucible#626]
As of 09532645133d39cda983bca67c2dbb91d05e4373, these options to `crux-llvm` appear in the `--help`, but not in the README. Not sure if this is a problem, but the README doesn't say anything about not being comprehensive.
```
--branch-coverage
--entry-point=SYMBOL
--fail-fast
--floating-point=floating-point
--force-offline-goal-solving
--hash-consing
--lax-arithmetic
--lazy-compile
--no-unsat-cores
--online-solver-output=FILE
--opt-loop-merge
--quiet
--skip-incomplete-reports
--skip-print-failures
--skip-report
--skip-success-reports
```

**Comment by atomb** [comment]
This should be solved by #655, but I'd love to make it automatically kept in sync.
