### ISSUE TITLE
crucible-llvm: Update to the latest version of the "versions" package

### ISSUE THREAD

**Issue by langston-barrett** [GaloisInc/crucible#640]
crucible-llvm depends on `versions` version `<4.0`:

https://github.com/GaloisInc/crucible/blob/950a629478354204f2cb72e46a4dc3078b5a459a/crux-llvm/crux-llvm.cabal#L99

However, What4 now requires `versions` version `>=4.0`:

https://github.com/GaloisInc/what4/blob/f57f852ed856d2a99d3edccf3b6c9e06bc1890b3/what4/what4.cabal#L93

So to update the What4 submodule, we'll need to support this next version of versions first.

**Comment by robdockins** [comment]
I'm working on an omnibus update to crucible that includes this.

**Comment by langston-barrett** [comment]
> I'm working on an omnibus update to crucible that includes this.

Rad, thanks for letting me know!
