### ISSUE TITLE
Failure encountered while generating a Crucible CFG: insertValue was expected to return base value of same type

### ISSUE THREAD

**Issue by steveyko** [GaloisInc/crucible#657]
I have encountered the following error message while running a SAW script.

```
[00:49:15.439] Stack trace:
"llvm_load_module" (/home/stevko/dev/saw/src/preprocessing/example.saw:1:6-1:22):
Failure encountered while generating a Crucible CFG: at /cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.46/src/print.rs:75:6: insertValue was expected to return base value of same type
```

The error occurs when loading my .bc file. My code is written in Rust, and I generated the .bc file with nightly-2020-05-07-x86_64-unknown-linux-gnu, which uses rustc 1.45.0-nightly (LLVM 9). If I switch to 1.37.0-x86_64-unknown-linux-gnu, which uses rustc 1.37.0 (LLVM 8), I do not get the error.

I am guessing that LLVM 9 is not officially supported, but I thought I would report it in case it's helpful.

I looked into this a bit, and it looks like the error is coming from the following LLVM code:

```
; Function Attrs: norecurse nounwind nonlazybind readnone uwtable
define internal { i64*, i64 } @_ZN9backtrace5print12BacktraceFmt5frame17h2c25360a8257f616E(%"print::BacktraceFmt"* align 8 dereferenceable(40)) unnamed_addr #23 !dbg !6981 {
  %2 = getelementptr inbounds %"print::BacktraceFmt", %"print::BacktraceFmt"* %0, i64 0, i32 0, i64 0, !dbg !6982
  %3 = insertvalue { i64*, i64 } undef, i64* %2, 0, !dbg !6983
  %4 = insertvalue { i64*, i64 } %3, i64 0, 1, !dbg !6983
  ret { i64*, i64 } %4, !dbg !6983
}
```

Specifically, the following line:
```
  %4 = insertvalue { i64*, i64 } %3, i64 0, 1, !dbg !6983
```

I also looked at what crucible does, and the error mainly comes from [the following block](https://github.com/GaloisInc/crucible/blob/master/crucible-llvm/src/Lang/Crucible/LLVM/Translation/Instruction.hs#L378):

```
           x' <- insertValue (BaseExpr tpr (getStruct idx x)) v is
           case x' of
             BaseExpr tpr' x''
               | Just Refl <- testEquality tpr tpr' ->
                    return $ BaseExpr (StructRepr ctx) (setStruct ctx x idx x'')
             _ -> fail "insertValue was expected to return base value of same type"
```

There, insertValue is returning ZeroExpr ('is' is [] and 'v' is i64 0), and so it fails.

If I simply add 'ZeroExpr _ -> return v', the problem goes away, but I am not sure if that's the right way to handle it.

**Comment by robdockins** [comment]
The following fairly minimal LLVM assembly is sufficient to reproduce in `crux-llvm` with LLVM 11.

```
define internal { i64*, i64 } @insertzero(i64*) {
  %2 = getelementptr inbounds i64, i64* %0, i64 0
  %3 = insertvalue { i64*, i64 } undef, i64* %2, 0
  %4 = insertvalue { i64*, i64 } %3, i64 0, 1
  ret { i64*, i64 } %4
}

define i64 @main () {
  %x = alloca [16 x i8], align 16
  %y = bitcast [16 x i8]* %x to i64*
  %z = call { i64*, i64 } @insertzero(i64* %y)
  %v = extractvalue { i64*, i64 } %z, 1
  ret i64 %v
}
```

```
$ cabal run crux-llvm -- insertzero.ll
Up to date
user error (Failure encountered while generating a Crucible CFG: at internal: insertValue was expected to return base value of same type)
```

**Comment by robdockins** [comment]
Turns out, we are also missing translation cases for `extractvalue` and `insertvalue` at array types.
