### ISSUE TITLE
Implement profiling hooks

### ISSUE THREAD

**Issue by atomb** [GaloisInc/crucible#67]
Now that the more fine-grained execution mechanism is in place, it would be nice to add support for tracing key events during symbolic execution (branches, merges, satisfiability checks, etc.) to make profiling more straightforward. Something in the spirit of this:

https://2018.splashcon.org/event/splash-2018-oopsla-finding-code-that-explodes-under-symbolic-evaluation

**Comment by robdockins** [comment]
Quite a bit of progress has been made on this front now.  With the new small-step evaluator, it's pretty easy to get in and add profiling support just by instrumenting the main execution loop.
See: https://github.com/GaloisInc/crucible/blob/master/crucible/src/Lang/Crucible/Simulator/Profiling.hs

The crucible-c frontend now has a basic ability to produce JSON profiling reports that can be plugged into a UI front end and explored.

We still need better support for reporting metrics, and I'd like to enhance somewhat the information we get out about the purpose and results of solver calls.

**Comment by robdockins** [comment]
I think we can close this now, after @lukemaurer's work on profiling improvements, e.g. 1546a81bbdc2f3e36d85b85209afe044661a63df.
