### ISSUE TITLE
crucible-wasm fails to compile on GHC 8.8 or later due to wasm dependency

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/crucible#671]
Attempting to build `crucible-wasm` with GHC 8.8 or later will fail like so:

```
$ cabal build crucible-wasm
Build profile: -w ghc-8.10.4 -O1
In order, the following will be built (use -v for more details):
 - wasm-1.0.0 (lib) (requires build)
 - crucible-wasm-0.1 (lib) (first run)
 - crucible-wasm-0.1 (exe:crucible-wasm) (first run)
Starting     wasm-1.0.0 (lib)
Building     wasm-1.0.0 (lib)

Failed to build wasm-1.0.0.
Build log (
/home/rscott/.cabal/logs/ghc-8.10.4/wasm-1.0.0-5f451f7fc79852fc9bb8faa579cce09507fe797b4a8927e81a33b0f55496ad89.log
):
Configuring library for wasm-1.0.0..
Preprocessing library for wasm-1.0.0..
Building library for wasm-1.0.0..
[ 1 of 11] Compiling Language.Wasm.FloatUtils ( src/Language/Wasm/FloatUtils.hs, dist/build/Language/Wasm/FloatUtils.o, dist/build/Language/Wasm/FloatUtils.dyn_o )
[ 2 of 11] Compiling Language.Wasm.Lexer ( dist/build/Language/Wasm/Lexer.hs, dist/build/Language/Wasm/Lexer.o, dist/build/Language/Wasm/Lexer.dyn_o )

src/Language/Wasm/Lexer.x:16:1: warning: [-Wunused-imports]
    The import of ‘Control.Applicative’ is redundant
      except perhaps to import instances from ‘Control.Applicative’
    To import instances alone, use: import Control.Applicative()
   |
16 | import Control.Applicative ((<$>))
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

templates/wrappers.hs:191:1: warning: [-Wunused-imports]
    The import of ‘Data.Word’ is redundant
      except perhaps to import instances from ‘Data.Word’
    To import instances alone, use: import Data.Word()

templates/wrappers.hs:195:1: warning: [-Wunused-imports]
    The qualified import of ‘Data.Char’ is redundant
      except perhaps to import instances from ‘Data.Char’
    To import instances alone, use: import Data.Char()
[ 3 of 11] Compiling Language.Wasm.Structure ( src/Language/Wasm/Structure.hs, dist/build/Language/Wasm/Structure.o, dist/build/Language/Wasm/Structure.dyn_o )
[ 4 of 11] Compiling Language.Wasm.Parser ( dist/build/Language/Wasm/Parser.hs, dist/build/Language/Wasm/Parser.o, dist/build/Language/Wasm/Parser.dyn_o )
[ 5 of 11] Compiling Language.Wasm.Builder ( src/Language/Wasm/Builder.hs, dist/build/Language/Wasm/Builder.o, dist/build/Language/Wasm/Builder.dyn_o )
[ 6 of 11] Compiling Language.Wasm.Binary ( src/Language/Wasm/Binary.hs, dist/build/Language/Wasm/Binary.o, dist/build/Language/Wasm/Binary.dyn_o )

src/Language/Wasm/Binary.hs:157:19: error:
    • No instance for (MonadFail PutM) arising from a use of ‘fail’
    • In the expression:
        fail
          "Current WebAssembly spec does not support returning more then one value"
      In an equation for ‘putResultType’:
          putResultType _
            = fail
                "Current WebAssembly spec does not support returning more then one value"
    |
157 | putResultType _ = fail "Current WebAssembly spec does not support returning more then one value"
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build wasm-1.0.0 (which is required by exe:crucible-wasm from
crucible-wasm-0.1). See the build log above for details.
```

I'm not sure what we should do about this. Perhaps we should request that the maintainer of `wasm` upload a new version to Hackage. Alternatively, perhaps we should vendor in our own fork of `wasm` until a new version appears on Hackage.

**Comment by RyanGlScott** [comment]
Another thing I've noticed recently is that `wasm-1.0.0` on Hackage constrains `containers < 0.6`, which effectively forces me to recompile everything with `containers-0.5.*` whenever I try to build anything in the `crucible` repo. I can work around this locally by putting `allow-newer: wasm:containers` in my `cabal.project.local` file, but I imagine that this results in a lot of wasted work on CI.

**Comment by kquick** [comment]
The haskell `wasm` project recently accepted some PR updates that make it compatible with crucible-wasm.  At some point, these should be available via Hackage, but for the time being, using the wasm repository instead of hackage will allow building.

**Comment by RyanGlScott** [comment]
OK. In that case, I'd advocate checking in `wasm` as a submodule, unless someone has an objection to that idea.

**Comment by kquick** [comment]
Sounds reasonable to me.

**Comment by RyanGlScott** [comment]
It turns out that `wasm` is _already_ a submodule—I just overlooked that part of `.gitmodules`. However, the [`haskell-wasm`](https://github.com/SPY/haskell-wasm) repo doesn't have a `.cabal` file (just a `package.yaml` file), so it isn't picked up by `cabal`.

**Comment by RyanGlScott** [comment]
I suppose we could instruct developers to run `hpack` inside of the `haskell-wasm` submodule to generate the `.cabal` file, but that's not even the only hurdle. On top of that, the version number for `wasm` in the `master` branch is smaller (?!) than what is on Hackage, and moreover, it exports fewer modules. In fact, `crucible-wasm` fails when built against commit SPY/haskell-wasm@36eacf16972c86e036d5d521a78af7f8e7031372:

```
[3 of 6] Compiling Lang.Crucible.Wasm.Instantiate ( src/Lang/Crucible/Wasm/Instantiate.hs, interpreted )

src/Lang/Crucible/Wasm/Instantiate.hs:34:1: error:
    Could not load module ‘Language.Wasm.Validate’
    it is a hidden module in the package ‘wasm-0.1.0’
    Use -v (or `:set -v` in ghci) to see a list of the files searched for.
   |
34 | import qualified Language.Wasm.Validate as Wasm
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by kquick** [comment]
Sorry, I had an unpushed update: https://github.com/GaloisInc/crucible/pull/686   This should solve the build issue.

Yes, hpack is needed for haskell-wasm; I don't know if there's a way that could be automated as part of a cabal.

I can't speak for the haskell-wasm version management.

**Comment by RyanGlScott** [comment]
As of # #687, I can successfully build `crucible-wasm` on GHC 8.10.4, so I'll declare this issue as fixed.
