### ISSUE TITLE
Spliced LLVMOverride expressions are bloated due to dataToExpQ

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/crucible#672]
If I compile `crux-llvm`'s `Crux.LLVM.Overrides` module with `-ddump-splices` enabled, you'll see many expressions of the following form:

```
src/Crux/LLVM/Overrides.hs:305:18-46: Splicing expression
    Language.Haskell.TH.Quote.quoteExp
      llvmOvr " void @__VERIFIER_error( ) "
  ======>
    ((LLVMOverride
        Text.LLVM.AST.Declare
          {Text.LLVM.AST.decRetType = Text.LLVM.AST.PrimType
                                        Text.LLVM.AST.Void,
           Text.LLVM.AST.decName = Text.LLVM.AST.Symbol
                                     (((:) '_')
                                        (((:) '_')
                                           (((:) 'V')
                                              (((:) 'E')
                                                 (((:) 'R')
                                                    (((:) 'I')
                                                       (((:) 'F')
                                                          (((:) 'I')
                                                             (((:) 'E')
                                                                (((:) 'R')
                                                                   (((:) '_')
                                                                      (((:) 'e')
                                                                         (((:) 'r')
                                                                            (((:) 'r')
                                                                               (((:) 'o')
                                                                                  (((:) 'r')
                                                                                     [])))))))))))))))),
           Text.LLVM.AST.decArgs = [], Text.LLVM.AST.decVarArgs = False,
           Text.LLVM.AST.decAttrs = [], Text.LLVM.AST.decComdat = Nothing})
       Empty)
      UnitRepr
```

This isn't just an artifact of the way `-ddump-splices` prints strings—it's literally consing each character in the string `"__VERIFIER_error"` one at a time. GHC can often compile string literals more efficiently, so it's possible that this might be impacting the compile-time performance of the `Crux.LLVM.Overrides` module. Even if it doesn't, it makes type errors involving these expressions quite unpleasant to deal with, as they fill up your terminal rather quickly.

The culprit is the use of the `dataToExpQ` function in `crucible-llvm`'s `Lang.Crucible.LLVM.QQ` module:

https://github.com/GaloisInc/crucible/blob/739f0e8a7ebdced47d43347ee822595b51973181/crucible-llvm/src/Lang/Crucible/LLVM/QQ.hs#L236-L249

`dataToExpQ` will turn a value into a `Q Exp` by way of its `Data` instance. The `Data` instance for `Strings` (i.e., `[Char]`), however, will handle each character in the list individually, resulting in the bloated expression above. A more compact way to turn the `String` into a `Q Exp` would be to use `Language.Haskell.TH.Syntax.lift`. The following is a quick-and-dirty way of accomplishing this:

```diff
diff --git a/crucible-llvm/src/Lang/Crucible/LLVM/QQ.hs b/crucible-llvm/src/Lang/Crucible/LLVM/QQ.hs
index 60391f34..d693e1f9 100644
--- a/crucible-llvm/src/Lang/Crucible/LLVM/QQ.hs
+++ b/crucible-llvm/src/Lang/Crucible/LLVM/QQ.hs
@@ -246,7 +246,7 @@ liftQQDecl (QQDeclare ret nm args varargs) =
     |]
   where
   f (Left v)    = varE (mkName v)
-  f (Right sym) = dataToExpQ (const Nothing) sym
+  f (Right (L.Symbol sym)) = [| L.Symbol sym |]
 
 liftKnownNat :: Integral a => a -> Q Exp
 liftKnownNat n = [| knownNat @ $(litT (numTyLit (toInteger n))) |]
```

With that change, the `-ddump-splices` output for `Crux.LLVM.Overrides` becomes:

```
src/Crux/LLVM/Overrides.hs:305:18-46: Splicing expression
    Language.Haskell.TH.Quote.quoteExp
      llvmOvr " void @__VERIFIER_error( ) "
  ======>
    ((LLVMOverride
        Text.LLVM.AST.Declare
          {Text.LLVM.AST.decRetType = Text.LLVM.AST.PrimType
                                        Text.LLVM.AST.Void,
           Text.LLVM.AST.decName = Text.LLVM.AST.Symbol "__VERIFIER_error",
           Text.LLVM.AST.decArgs = [], Text.LLVM.AST.decVarArgs = False,
           Text.LLVM.AST.decAttrs = [], Text.LLVM.AST.decComdat = Nothing})
       Empty)
      UnitRepr
```

A cleaner way to accomplish this would be something like this:

```diff
diff --git a/crucible-llvm/src/Lang/Crucible/LLVM/QQ.hs b/crucible-llvm/src/Lang/Crucible/LLVM/QQ.hs
index 60391f34..d693e1f9 100644
--- a/crucible-llvm/src/Lang/Crucible/LLVM/QQ.hs
+++ b/crucible-llvm/src/Lang/Crucible/LLVM/QQ.hs
@@ -246,7 +246,7 @@ liftQQDecl (QQDeclare ret nm args varargs) =
     |]
   where
   f (Left v)    = varE (mkName v)
-  f (Right sym) = dataToExpQ (const Nothing) sym
+  f (Right sym) = lift sym
 
 liftKnownNat :: Integral a => a -> Q Exp
 liftKnownNat n = [| knownNat @ $(litT (numTyLit (toInteger n))) |]
```

However, that won't compile as-is because the `Symbol` data type from `llvm-pretty` does not have a `Lift` instance. There are other uses of `dataToExpQ` in `Lang.Crucible.LLVM.QQ` as well, but again, they're invoked on other data types from `llvm-pretty` which lack `Lift` instances.

**Comment by robdockins** [comment]
So, is the best solution to this to sink the right `Lift` instances down into `llvm-pretty`?

**Comment by RyanGlScott** [comment]
Right. In theory, we should be able to just attach `deriving Lift` clauses to `Symbol`, `PrimType`, and `Ident` in `llvm-pretty`. I looked into this briefly, but one complication is that the `DeriveLift` extension was introduced in GHC 8.0, but `llvm-pretty.cabal`'s version bounds on `base` seems to indicate that it supports pre-8.0 versions of GHC. In light of this, we could:

1. Tighten up the version bounds to only allow 8.0 or later
2. Use CPP so that `deriving Lift` is only used when building with 8.0 or later
3. Define the `Lift` instances by hand to support all versions of GHC

I'm not fond of option (3), as defining `Lift` instances by hand is tedious. I don't have a strong opinion between options (1) and (2). For what it's worth, the current version of `llvm-pretty` on Hackage (and its upstream `git` repo) doesn't seem to actually support pre-8.0 in practice, since if you try to compile it with GHC 7.10.3, it will error out:

```
Building library for llvm-pretty-0.11.0..

src/Text/LLVM/AST.hs:22:8:
    Could not find module ‘Data.Semigroup’
    It is a member of the hidden package ‘semigroups-0.19.1@2v1dfSOvrzj1tEQS2HrG7N’.
    Perhaps you need to add ‘semigroups’ to the build-depends in your .cabal file.
    It is a member of the hidden package ‘semigroups-0.19.1@FDpEROrPB105hC2RCShNv5’.
    Perhaps you need to add ‘semigroups’ to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```

So perhaps option (1) is needed anyway.

**Comment by RyanGlScott** [comment]
I've submitted an issue upstream at elliottt/llvm-pretty#81.
