### ISSUE TITLE
Add support for unsat cores to What4

### ISSUE THREAD

**Issue by atomb** [GaloisInc/crucible#68]
Several solvers, including CVC4 and, recently, Yices, support generation of unsat cores. For clients that can make use of these, it would be convenient for What4 to support parsing and returning them along with unsat results.

**Comment by robdockins** [comment]
An important design decision we need to address here is: how do manage the annotation of portions of formulae in `what4` so they can be referred to by the generated unsat cores?

Should users be able to have direct control over annotations? Should they be transparently and automatically added at the granularity of individual `Assume`s? etc.

**Comment by atomb** [comment]
We've considered the idea of allowing labels on (sub)formulas for a variety of purposes (unsat cores, indicating "important" variables, and controlling MaxSAT, among other things), so I'm inclined to say that we should allow annotations on any `what4` formula. Perhaps things like `Assume` in symbolic execution would automatically add those annotations, but I'd like it if any `what4` client could decide how to annotate a formula, too.

Another question is how structured those annotations should be, and how much `what4` itself should understand them. I don't know if I have a strong opinion about that yet.

Yet another question is how much we want to expose this mechanism to the user of tools built around `what4`. For the moment, I think we can have tools like `crucible-c` make the decision, but we may want to keep in mind the idea of allowing some sort of user annotation (expressed in source language terms) that would affect what annotations get added. That's farther down the road, though.

**Comment by robdockins** [comment]
We now have support for unsat cores on the `yices-master` branch.  I've not yet merged this branch into `master` because it depends on behavior in an unreleased version of yices.

**Comment by joehendrix** [comment]
I don't know if this is useful for this, but I noticed recently that SMTLIB has support for naming subterms in a formula.  I added support for generating the syntax using the low-level SMTLIB interface in https://github.com/GaloisInc/crucible/commit/d1982d4e8b287705dac714b40fdaccef59510c49.  This would need to be connected to the `what4` interface if it turns out to be useful.

**Comment by robdockins** [comment]
I've now merged the code that makes unsat cores available from what4 and via crucible online backends.

We may also want to expose unsat cores in other ways at a later time, but for now I'm going to close this.
