### ISSUE TITLE
Handling LLVM debug information

### ISSUE THREAD

**Issue by langston-barrett** [GaloisInc/crucible#696]
In both `uc-crux-llvm` and SAW (at least), we sometimes need to extract e.g. function argument names or struct field names from LLVM's debug info. Where should the code to do this live?

See discussion here: https://github.com/GaloisInc/crucible/pull/673#discussion_r599103951

**Comment by atomb** [comment]
This code perhaps belongs in either `llvm-pretty` or `llvm-pretty-bc-parser`, since it only uses those data structures.
