### ISSUE TITLE
crucible-llvm: Implement undefExpand for float types

### ISSUE THREAD

**Issue by langston-barrett** [GaloisInc/crucible#705]
I encountered this error today:
```
[Crux] user error (Failure encountered while generating a Crucible CFG: at src/numfmt.c:323:12: cannot undef expand type: long double)
```
This is not actually a user error, but rather [a FIXME](https://github.com/GaloisInc/crucible/blob/63641d8cc27b4ef9f6c195695620c2f1c4a6796c/crucible-llvm/src/Lang/Crucible/LLVM/Translation/Expr.hs#L307):
```haskell
--undefExpand (L.PrimType (L.FloatType _ft)) _k = error "FIXME undefExpand: float types"
```
Here's the bitcode:
[coreutils.bc.zip](https://github.com/GaloisInc/crucible/files/6223556/coreutils.bc.zip)

**Comment by langston-barrett** [comment]
The only "base" (non-struct, non-array) type supported by `undefExpand` is pointers, which expand to [`BVUndef`](https://github.com/GaloisInc/crucible/blob/7235567d16039cfff6cddc5e895caaeef956106a/crucible/src/Lang/Crucible/CFG/Expr.hs#L578):
```haskell
  -- generate an "undefined" bitvector value
  BVUndef :: (1 <= w) => NatRepr w -> App ext f (BVType w)
```
Maybe it would be appropriate to add a `FloatUndef` constructor and basically copy however `BVUndef` is treated?
```haskell
  -- generate an "undefined" float value
  FloatUndef :: !(FloatInfoRepr fi) -> App ext f (BVType w)
```

**Comment by robdockins** [comment]
Everything about `undef` sucks.  I've been hoping that the conversation about LLVM poison/undef would settle down so we could actually do this right, but it just hasn't done that yet, as far as I know.  What `BVUndef` does is wrong (create a fresh uninterpreted value), and I'd like to remove it... but it gets emitted to much to just ignore it.  We can do the same for floats, I guess.
