### ISSUE TITLE
'interpBr' function of forward fixpoint 

### ISSUE THREAD

**Issue by victorybringer** [GaloisInc/crucible#729]
I am a  foreign student without good english and trying to use the forward fixpoint  framework to do symbolic executing , what can I do in 'interpBr' function  (for example , I want to generate path conditions in the form of SBV Bool  and pass them to the successors .

There are two examples named Max and Even in the test folder of crucible  and I try to learning from these two tests.
![QQ截图20210419194907](https://user-images.githubusercontent.com/47849000/115231635-5e7e8800-a148-11eb-9847-a2f4ae970c49.png)
but the  'interpBr' functions in these two files just return 
Nothing  .How can I deal with JumpTarget  in Max and Even Problems.

**Comment by victorybringer** [comment]
Is there any way to  get the actual arguments from the Jump Target in a specific problem like Max and Even without having rigid types problems

**Comment by travitch** [comment]
A few points that I hope will help:
1. Note that the arguments to a basic block (expressed as the arguments to the jump target / the arguments of the jump instruction / the initial locals in scope at the beginning of a block) are represented by the `ctx` type parameter
2. The values you that should be returned by your implementation of `interpBr` are be the abstract values that are in scope at the beginning of the true and false successors of the branch (respectively, the `fst` and `snd`)
3. If you return `Nothing` for a branch, the computed abstract values for each local will be passed along without modification
4. If you return a `Just` value from `interpBr`, it will override the naturally computed ones (and you can make it anything you want - termination is only guaranteed if you your lattice is actually monotonic)
5. The abstract values for all of the arguments to the jump target are provided in the 5th argument (the `PointAbstraction` with the `ctx` type parameter); the concrete values are not accessible here, I suppose they could be, but I think there might be a good argument for only relying on the abstract values (lest you risk inconsistency) - I'm not sure how good that argument is, though
6. For your second question, if you need to inspect the abstract values of the arguments to the branch instruction, you'll need to pattern match on the `CtxRepr` of the `JumpTarget`. Note that `CtxRepr ctx` is just a `Assignment TypeRepr ctx`

**Comment by travitch** [comment]
Closing this for now - feel free to reopen if there are additional questions
