### ISSUE TITLE
crux-llvm crashes with `--target=i386-unknown-linux-elf` and `ub-sanitizers: [ "signed-integer-overflow" ]`

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/crucible#737]
The following program, which is a minimized version of [this SV-COMP benchmark](https://github.com/sosy-lab/sv-benchmarks/blob/99d37c5b4072891803b9e5c154127c912477f705/c/array-programs/partial_mod_count_1.c):

```c
// test.c

int N = 10;

int main() {
  int i;
  int j = 0;
  int a[N];

  for (i = 0; i < N; i++) {
    a[i] = 0;
  }

  for (i = 0; i < N; i++){
    if (a[i] == 0) {
      j++;
    }
  }

  return 0;
}
```

Will crash `crux-llvm` under the right circumstances. To reproduce, you will need the following configuration file:

```
-- test.crux
ub-sanitizers: [ "signed-integer-overflow" ]
```

If `crux-llvm` assumes a 32-bit architecture, it will fail with the following error:

```
$ cabal run exe:crux-llvm -- --config test.crux --target=i386-unknown-linux-elf test.c 
Up to date
[Crux] user error (Failure encountered while generating a Crucible CFG: at test.c:8:7: Invalid alloca argument: Just (Typed {typedType = PrimType (Integer 32), typedValue = ValIdent (Ident "1")}))
```

Note that this does _not_ happen if it assumes a 64-bit architecture:

```
$ cabal run exe:crux-llvm -- --config test.crux --target=x86_64-unknown-linux-elf test.c 
Up to date
[Crux] Using pointer width: 64 for file crux-build/crux~test.bc
[Crux] Simulating function "main"
[Crux] All goals discharged through internal simplification.
[Crux] Overall status: Valid.
```

**Comment by atomb** [comment]
I wonder if we have a baked-in assumption that `alloca` takes a 64-bit argument even when the pointer size is 32 bits?

**Comment by RyanGlScott** [comment]
Some further investigation reveals that this is a problem introduced in more recent versions of LLVM. If I use LLVM 7, then the issue goes away:

```
$ CLANG=clang-7 LLVM_LINK=llvm-link-7 cabal run exe:crux-llvm -- --config test.crux --target=i386-unknown-linux-elf test.c 
Up to date
[Crux] Using pointer width: 32 for file crux-build/crux~test.bc
[Crux] Simulating function "main"
[Crux] All goals discharged through internal simplification.
[Crux] Overall status: Valid.
```

However, the issue surfaces with LLVM 10:

```
$ CLANG=clang-10 LLVM_LINK=llvm-link-10 cabal run exe:crux-llvm -- --config test.crux --target=i386-unknown-linux-elf test.c 
Up to date
[Crux] user error (Failure encountered while generating a Crucible CFG: at test.c:8:7: Invalid alloca argument: Just (Typed {typedType = PrimType (Integer 32), typedValue = ValIdent (Ident "1")}))
```

I suspect the issue relates to assumptions that `crucible-llvm` makes about pointer width. This is the part of the code where the `Invalid alloca argument` error comes from:

https://github.com/GaloisInc/crucible/blob/3e1184bc65a81b50eaf6770d63005c1029dde6dd/crucible-llvm/src/Lang/Crucible/LLVM/Translation/Instruction.hs#L1463-L1479

If `n` happens to be an LLVM pointer with a width that is not equal to `PtrWidth`, then the error will occur. I did some `putStrLn` tracing, and it turns out that with LLVM 10, `crucible-llvm` thinks that `PtrWidth` is 64, despite the fact that we compiled the program with `--target=i386-unknown-linux-elf`! How did this happen?

Currently, `crucible-llvm` infers the value of `PtrWidth` by looking at the `target datalayout` of a bitcode file:

https://github.com/GaloisInc/crucible/blob/79428012dae4e3c922f75c6f41f418c8aacca665/crucible-llvm/src/Lang/Crucible/LLVM/DataLayout.hs#L298-L318

This code will iterate over each layout spec in the `target datalayout`, and it will deem the last `PointerSize` spec that it sees as the value of `PtrWidth` for the rest of the `crux-llvm` invocation. With LLVM 7, there happens to be only one `PointerSize` spec—see the `-p:32:32` bit below:

```
; ModuleID = 'crux~test.bc'
source_filename = "llvm-link"
target datalayout = "e-m:e-p:32:32-f64:32:64-f80:32-n8:16:32-S128"
target triple = "i386-unknown-linux-elf"
```

With LLVM 10, however, the story is different:

```
; ModuleID = 'crux~test.bc'
source_filename = "llvm-link"
target datalayout = "e-m:e-p:32:32-p270:32:32-p271:32:32-p272:64:64-f64:32:64-f80:32-n8:16:32-S128"
target triple = "i386-unknown-linux-elf"
```

There are now _multiple_ `-p` specs, each corresponding to a different address space. In particular, note that the last spec, `-p272:64:64`, happens to use a pointer of size 64, which is what causes `crux-llvm` to think that `PtrWidth` is 64.

What should we do about this? Perhaps we should be determining `PtrWidth` by using the `target triple` instead, as suggested by this comment:

https://github.com/GaloisInc/crucible/blob/79428012dae4e3c922f75c6f41f418c8aacca665/crucible-llvm/src/Lang/Crucible/LLVM/Translation/Monad.hs#L108-L110

I'm unclear how much effort would be required to make `llvm-pretty` capture this information.

**Comment by robdockins** [comment]
Interesting.  I guess we've been implicitly assuming that there would only be one address space specified.  I guess we should really take the "default" address space as the one of interest (the first one, with an implicit address space number of 0).  I'm a bit worried about those other address spaces though: what are they for, and does clang emit code that actually uses them?  Supporting more than one address space would be pretty tricky, I think; we'd have to really rethink how pointer width information is piped around.

**Comment by RyanGlScott** [comment]
This change was introduced in [this LLVM commit](https://reviews.llvm.org/D64931). Based on my understanding of the [accompanying discussion](https://lists.llvm.org/pipermail/llvm-dev/2019-July/134035.html), `-p270:32:32-p271:32:32-p272:64:64` are hardcoded certain address spaces which are used to implement the `__ptr32`, `__ptr64`, `__sptr`, `__uptr` pointer type qualifiers, which were originally introduced in MSVC. So yes, `clang` does support multiple address spaces, although perhaps only under limited circumstances.

>  I guess we should really take the "default" address space as the one of interest (the first one, with an implicit address space number of 0).

Indeed, this seems like the best course of action for now at least. Perhaps we could do this and advertise our lack of support for differently-sized address spaces somewhere?
