### ISSUE TITLE
crux-llvm fails on C programs with .i file extension

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/crucible#745]
Suppose both `test.c` and `test.i` contain this program:

```c
#include <crucible.h>
#include <stdint.h>

int main() {
  int8_t x = crucible_int8_t("x");
  check(x == x);
  return 0;
}
```

Running `crux-llvm` on `test.c` will work:

```
$ cabal run exe:crux-llvm -- --sim-verbose=2 test.c
Up to date
[CLANG] clang "-c" "-DCRUCIBLE" "-emit-llvm" "-g" "-I" "." "-I" "/home/rscott/Documents/Hacking/Haskell/crucible/crux-llvm/./c-src/includes" "-O1" "-o" "crux-build/test.bc" "test.c"
[Crux] Checking "test.c"
[Crux] Using pointer width: 64 for file crux-build/crux~test.bc
[Crux] Simulating function "main"
[Crux] Attempting to prove verification conditions.
[Crux] Simulation complete.
[Crux] Goal status:
[Crux]   Total: 1
[Crux]   Proved: 1
[Crux]   Disproved: 0
[Crux]   Incomplete: 0
[Crux]   Unknown: 0
[Crux] Overall status: Valid.
```

Whereas running `crux-llvm` on `test.i` will _not_ work:

```
$ cabal run exe:crux-llvm -- --sim-verbose=2 test.i
Up to date
[CLANG] clang "-c" "-DCRUCIBLE" "-emit-llvm" "-g" "-I" "." "-I" "/home/rscott/Documents/Hacking/Haskell/crucible/crux-llvm/./c-src/includes" "-O1" "-o" "crux-build/test.bc" "test.i"
[Crux] `clang` compilation failed.
*** Exit code: 1
*** Standard out:
*** Standard error:
   clang: warning: argument unused during compilation: '-I .' [-Wunused-command-line-argument]
   clang: warning: argument unused during compilation: '-I /home/rscott/Documents/Hacking/Haskell/crucible/crux-llvm/./c-src/includes' [-Wunused-command-line-argument]
   test.i:1:10: fatal error: 'crucible.h' file not found
   #include <crucible.h>
            ^~~~~~~~~~~~
   1 error generated.
```

It would be convenient to have `crux-llvm` work on C files with an `.i` file extension, as that is common in [SV-COMP's benchmark programs](https://github.com/sosy-lab/sv-benchmarks).

**Comment by RyanGlScott** [comment]
Ah, this is because `clang` treats `.i` files as already having been preprocessed, which is why it ignores the `-I` flags. (I concocted my own `.i` file that uses `#include <crucible.h>`, which is how I stumbled upon this, but such a thing would normally not happen in most `.i` files.) To resolve this issue, we could:

1. Declare this as not a bug, since an `.i` file is not supposed to have `#include`s, or
2. Pass `-x c` to `clang` to force it to treat `.i` as an ordinary C file.

Option (2) would likely be too aggressive, as it would cause Clang to treat non-C files as C (e.g., `.cpp` files, which are likely C++, not C). Perhaps it would be worth making `crux-llvm` have its own flag to specify the input language? `-x` is already taken, alas, so it would have to be named something besides `-x`.

**Comment by atomb** [comment]
I'd be inclined to go with (1) unless we encounter `.i` files in the wild that actually need more pre-processing. FWIW, the `.i` files I normally encounter are the ones from SV-COMP, and they use the separate SV-COMP API for which they include declarations. So, under normal circumstances, `crucible.h` shouldn't be necessary. For things we write, I think using a `.c` extension and the `crucible.h` API is probably the best approach. There's also the option of passing the `-include blah.h` option to `clang` rather than adding a `#include` line in the source file.

**Comment by RyanGlScott** [comment]
> I'd be inclined to go with (1) unless we encounter `.i` files in the wild that actually need more pre-processing.

After some more thought, I'm inclined to agree, especially since it's less work. :)
