### ISSUE TITLE
SV-COMP: Get rid of unneeded overrides for `__VERIFIER_{assert,assume,error}`

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/crucible#804]
As of SV-COMP 2021, the `__VERIFIER_assume` and `__VERIFIER_error` functions are [no longer part of the competition ruleset](https://sv-comp.sosy-lab.org/2021/rules.php) as primitive functions. Instead, they are now defined in terms of other C functions. For instance, `__VERIFIER_error` now invokes `__assert_fail()`. As a result, the overrides for `__VERIFIER_assume` and `__VERIFIER_error` are not actually needed (and if a program is compiled with optimizations, the overrides will likely never be used anyway).

Similarly, `__VERIFIER_assert` is not actually an SV-COMP primitive, but rather a C function that call `abort()` depending on whether the argument is true or not.

I propose that we get rid of these overrides.

**Comment by robdockins** [comment]
Makes sense to me.
