### ISSUE TITLE
broken saw-script integration test

### ISSUE THREAD

**Issue by robdockins** [GaloisInc/crucible#81]
Recent crucible-jvm commits have broken the `test_crucible_jvm` integration test.  Seems like some problem with string handling.  Bisecting reveals the culprit to be commit 3fe7017aa734a3b9cecce51ace3161e4e9ea5461.

There's a lot of stuff in there so, I'm not entirely sure what might be going on.

**Comment by sweirich** [comment]
I need to pull in changes from https://github.com/sweirich/saw-script/tree/wip-crucible-jvm after I update it to master.  Unfortunately, after the merge from master, I can't build. As soon as I can figure out what my issue with the build is, I'll be able to fix this problem.

**Comment by atomb** [comment]
This seems to be fixed now.
