### ISSUE TITLE
CRUCIBLE define is missing in official Docker image

### ISSUE THREAD

**Issue by varosi-chaosgroup** [GaloisInc/crucible#818]
In the documentation - https://github.com/GaloisInc/crucible/tree/master/crux-llvm
There is mentioned "CRUCIBLE" define, but official Docker image at galoisinc/crux-llvm:0.4 is not defining this macro and the example from the documentation doesn't work with it.

**Comment by RyanGlScott** [comment]
Like with #817, I suspect that this is simply a matter of [the Docker image](https://hub.docker.com/r/galoisinc/crucible) not being recent enough. This was addressed in commit b763d49946fa07430b4e61e96ca15700c5e5d23d, and I can confirm that the example from the `crux-llvm` README does work if I use a build including that commit.

**Comment by varosi-chaosgroup** [comment]
Currently I didn't found a time to make whole setup without Docker to test from certain source line. But I think you're right and only official Docker image have to be updated by Galois, as it is uploaded with company account I think.

**Comment by RyanGlScott** [comment]
This should be included with thew recently published `ghcr.io/galoisinc/crux-llvm:0.5` Docker image.
