### ISSUE TITLE
Crucible panic when using SAW 

### ISSUE THREAD

**Issue by tegansiobhan** [GaloisInc/crucible#82]
I ran into the following panic when using the latest nightly build of SAW for MACs (https://saw.galois.com/builds/nightly/saw-0.2-2018-09-05-MacOSX-64.tar.gz)

You have encountered a bug in Crucible's implementation.
*** Please create an issue at https://github.com/GaloisInc/crucible/issues

%< --------------------------------------------------- 
  Revision:  de3f0f9ed60794624a6ea0921777080b0d6b47f9
  Branch:    HEAD
  Location:  Intrinsics.register_llvm_override
  Message:   Argument type mismatch when registering LLVM mss override.
             *** Override name: Symbol "llvm.objectsize.i64.p0i8"
CallStack (from HasCallStack):
  panic, called at src/Lang/Crucible/Panic.hs:11:9 in crucible-0.4-DND9C4WiHH7AxtfMml2CWw:Lang.Crucible.Panic
  panic, called at src/Lang/Crucible/LLVM/Intrinsics.hs:317:14 in crucible-llvm-0.1-KeRiwQXtoJRASDAERGm0CZ:Lang.Crucible.LLVM.Intrinsics
%< ---------------------------------------------------

**Comment by atomb** [comment]
It looks like the type of `llvm.objectsize.i64.p0i8` changed after version 4.0. We'll have to add a condition on the LLVM version for this override. As a workaround for the time being, you could try compiling your code with LLVM/Clang 4.0.1 or earlier.

**Comment by tegansiobhan** [comment]
Thank you! Converting to an old version of clang fixed this error.

**Comment by robdockins** [comment]
I'm going to close this as being subsumed by issue #108.
