### ISSUE TITLE
--no-compile option is missing in the official Docker image

### ISSUE THREAD

**Issue by varosi-chaosgroup** [GaloisInc/crucible#820]
So currently it is not possible to use custom defines "-D" compiler option, as I cannot use .bc files built externally.

Docker image: galoisinc/crux-llvm:0.4

I think that may be a newer image could be made.

**Comment by atomb** [comment]
Yeah, that image is from our last release, and a good amount has changed since then. We plan to do another release in September, and to enable nightly Docker images for Crux.

**Comment by RyanGlScott** [comment]
This should be fixed with the recently published `ghcr.io/galoisinc/crux-llvm:0.5` Docker image.
