### ISSUE TITLE
[Question] Is this error a bug or a sign of an intrinsic not being supported?

### ISSUE THREAD

**Issue by alext-w** [GaloisInc/crucible#825]
Hello Crucible team,

I'm trying (a current) SAW out on a certain code (compiled with Clang 10) that uses AVX2 intrinsics and I get the following error when calling the `crucible_execute_func` from the SAW file. As the error apparently comes from Crucible itself, I'm asking here - but please let me know if you think SAW's issue tracker would be a better place.

```
Symbolic execution failed.
Abort due to false assumption:
  <path/to/my/header/file>:247:18: error: in <function name>
  Failed to load function handle
  Details:
    No implementation or override found for pointer: "llvm.masked.load.v16i32.p0v16i32"
<...>
GlobalAlloc 11 0x0:[64] Immutable 1-byte-aligned [external function] llvm.masked.load.v16i32.p0v16i32
<...>
```

This seems to be caused by the `_mm512_maskz_loadu_epi32()` intrinsic used by that function, imported from the Clang's standard `immintrin.h` file.

Looking at the `crux-llvm` readme, I see it lists several intrinsics as "supported", but not this one. As I'm new to Crucible, could you please clarify - does this mean that intrinsic has to be supported by Crucible's code explicitly and it's not enough that the actual implementation is provided by that header file, or is this some kind of bug?

**Comment by alext-w** [comment]
Thanks @travitch, understood. So I guess this would be the same for many other similar intrinsics, right? Is there any detailed list of those supported? I also wonder how much effort is it to add one - do you have any guide or maybe old PRs/commits adding those I could take a look at, to gauge that?

**Comment by travitch** [comment]
Here is the list of current overrides: https://github.com/GaloisInc/crucible/blob/master/crucible-llvm/src/Lang/Crucible/LLVM/Intrinsics.hs#L153 (see https://github.com/GaloisInc/crucible/blob/master/crucible-llvm/src/Lang/Crucible/LLVM/Intrinsics/LLVM.hs for the low-level LLVM overrides).

There isn't really specific documentation on adding overrides, but those would serve as a good template. It looks like there are currently no variants of masked load to copy from.

**Comment by alext-w** [comment]
Thank you, let me take a look to see if I can help fix this.
