### ISSUE TITLE
Crucible panic from SAW equivalence proof 

### ISSUE THREAD

**Issue by tegansiobhan** [GaloisInc/crucible#84]
Thank you for your help in solving my previous issue. I am now using clang 3.9. However, as I've continued to write SAW code, I've encountered a new panic. Any thoughts? Thank you again!

You have encountered a bug in Crucible's implementation.
*** Please create an issue at https://github.com/GaloisInc/crucible/issues

%< --------------------------------------------------- 
  Revision:  de3f0f9ed60794624a6ea0921777080b0d6b47f9
  Branch:    HEAD
  Location:  MemModel.packMemValue
  Message:   Type mismatch when storing value.
             *** Expected storable type: bitvectorType 1
             *** Given crucible type: RecursiveRepr LLVM_pointer [BVRepr 1]
CallStack (from HasCallStack):
  panic, called at src/Lang/Crucible/Panic.hs:11:9 in crucible-0.4-DND9C4WiHH7AxtfMml2CWw:Lang.Crucible.Panic
  panic, called at src/Lang/Crucible/LLVM/MemModel.hs:527:3 in crucible-llvm-0.1-KeRiwQXtoJRASDAERGm0CZ:Lang.Crucible.LLVM.MemModel
%< ---------------------------------------------------

**Comment by robdockins** [comment]
Do you have a small example that triggers the panic? The style of error is one I've run into before, but I'm not sure what code path is triggering it.

**Comment by robdockins** [comment]
This appears to be the same as issue #109.  I believe it should be fixed as of fe51137096600ea9ab5d9b3be6962cab8d616db8.

If not, feel free to reopen.
