### ISSUE TITLE
`crucible-llvm`: `signbit` returns symbolic value, despite concrete input

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/crucible#850]
If you take the following program:

```c
#include <math.h>
#include <stdio.h>

#ifdef CRUCIBLE
# include <crucible.h>
#endif

int main() {
  double dy = -1;
  printf("%d\n", signbit(dy));
#ifdef CRUCIBLE
  check(signbit(dy) != 0);
#endif
  return 0;
}
```

And simulate it with `crux-llvm` and `-O0`, it will fail:

```
$ cabal run exe:crux-llvm -- test2.c -O0
Resolving dependencies...
Up to date
[Crux] Using pointer width: 64 for file crux-build/crux~test2.bc
[Crux] Simulating function main
????
[Crux] Attempting to prove verification conditions.
[Crux] *** debug executable: results/test2/debug-12
[Crux] *** break on line: 12
[Crux] Found counterexample for verification goal
[Crux]   test2.c:12:0: error: in main
[Crux]   crucible_assert
[Crux] Goal status:
[Crux]   Total: 1
[Crux]   Proved: 0
[Crux]   Disproved: 1
[Crux]   Incomplete: 0
[Crux]   Unknown: 0
[Crux] Overall status: Invalid.
```

Based on the results of `printf`, it appears that `crucible-llvm` thinks that the output of `signbit(dy)` is a symbolic value. I don't see why this would be the case, however, since `dy` is a concrete input. Moreover, compiling the program with `clang` causes it to output `1`, as expected.

**Comment by travitch** [comment]
The default solver for crux is yices, where the default interpretation of floating point operations is as mathematical reals. We don't do much evaluation (even concrete evaluation) in real mode.

If you try with z3, the default float mode is IEEE, which has a chance of evaluating that (though I don't know if it does or not)

**Comment by RyanGlScott** [comment]
D'oh, that's exactly right. Thanks!
