### ISSUE TITLE
Missing package lower bound for `config-schema`

### ISSUE THREAD

**Issue by brianhuffman** [GaloisInc/crucible#852]
Module `crux/src/Crux.SVCOMP.hs` uses the operator `<!>`, which it expects to import from module `Config.Schema` in package `config-schema`. However this was only added to the export list of `Config.Schema` in `config-schema-1.2.2.0`. The `crux.cabal` file needs a lower bound `config-schema >= 1.2.2.0`.

**Comment by RyanGlScott** [comment]
It's also used [here](https://github.com/GaloisInc/crucible/blob/59b1db232641d7587563e86d56d4a78330baf28c/crux-llvm/src/Crux/LLVM/Config.hs#L72-L74) in `crux-llvm`, so we should apply the same lower version bounds to `crux-llvm.cabal` as well.
