### ISSUE TITLE
`README`: Note that `cabal` does support coverage with 3.6.0.0 or later

### ISSUE THREAD

**Issue by RyanGlScott** [GaloisInc/crucible#884]
Currently, the `README` [says](https://github.com/GaloisInc/crucible/tree/796d1f595e7cbcd421e68050fa5cc864327b7aab#testing-and-coverage):

> Testing with coverage tracking is currently only available via `stack`, as `cabal new-*` [does not yet support coverage](https://github.com/haskell/cabal/issues/5213). Use `scripts/stack-test-coverage.sh` to generate a coverage report for all test suites.

As pointed out in https://github.com/GaloisInc/crucible/issues/874#issuecomment-934493138, however, the claim that `cabal` doesn't support coverage isn't quite true these days. The issue linked above haskell/cabal#5213, has since been fixed, and the fix is present in `cabal-3.6.0.0` and later. We should change the wording in the `README` to reflect this.

**Comment by peterbecich** [comment]
Are you running `cabal test --enable-coverage all` , `cabal test --enable-coverage --disable-library-coverage all`, or something else?

This may still be unresolved: https://github.com/haskell/cabal/issues/6440
Using Cabal 3.6.2.0 and the latest commit of `crucible`, I get:
```
% cabal test --enable-coverage all
Resolving dependencies...
Error:
    Internal libraries only supported with per-component builds.
    Per-component builds were disabled because program coverage is enabled
    In the package 'tasty-sugar-1.1.0.0'
```

Thanks

**Comment by RyanGlScott** [comment]
Sigh. Admittedly, I hadn't actually tried running `cabal test --enable-coverage` before posting this issue, but you're correct in observing that it doesn't work out of the box just yet. I guess we'll just have to mention the workaround from haskell/cabal#6440 in the `README`.

**Comment by RyanGlScott** [comment]
Done in #1098.
