### ISSUE TITLE
`scripts/build_sandbox.sh` does not pull submodules for abcBridge

### ISSUE THREAD

**Issue by m10f** [GaloisInc/crucible#91]
When trying to follow the build instructions, the build fails due to a fairly mysterious error which is fixed by getting the submodules for `dependencies/abcBridge` - it is probably the case that the `build_sandbox.sh` script should also fetch the submodules

**Comment by robdockins** [comment]
Humm, indeed.

Actually, now that the crucible repository itself contains some top-level projects (`crucible-c`, `crucible-jvm`) I think it's time to revisit the question getting rid of the `build_sandbox` script and transitioning to git submodules.

The rationale used to be that crucible was really only being used as a dependency of other projects, but that isn't really true anymore.

**Comment by robdockins** [comment]
OK, I've updated the repository to use submodules.  Now the `build-sandbox.sh` script doesn't really do anything other than call the git commands to fetch submodules recursively.  Hopefully that fixes this issue.
