### ISSUE TITLE
Delete PtrToIntConst constructor

### ISSUE THREAD

**Issue by siddharthist** [GaloisInc/crucible#94]
A `PtrToIntConst` is
```haskell
  -- | A special marker for pointer constants that have been cast as an integer type.
  PtrToIntConst :: !LLVMConst -> LLVMConst
```
As such, it could only contain pointers. Only some `LLVMConst` expressions could possibly be interpreted as symbols, so this type should be refactored to reflect that:
 - `ZeroConst`: ? Is this the null pointer?
 - `SymbolConst`: Definitely a pointer
 - `IntConst`: ? Could these get cast to pointers?
 - All the other constructors are not pointers: `FloatConst`, `DoubleConst`, `ArrayConst`, `VectorConst`, `StructConst`.

**Comment by robdockins** [comment]
Originally, the idea here was that `PtrToIntConst` should indeed only be things that are "actually" pointers (for some notion of actually) and that the integer to pointer conversions would only succeed on things that had a `PtrToIntConst` wrapped around them.

This is too restrictive, however; clang will sometimes produce code that doesn't follow the rules we had in mind.  The right thing to do is to delete `PtrToIntConst` and essentially erase the type-level distinction between pointers and integers of the right width.  Pointer/integer confusion issues will thus be delayed until runtime, just as they currently are for non-constant expressions.  This is probably unavoidable as long as clang insists on producing code that casts raw offset values as pointers and such.

**Comment by robdockins** [comment]
Done in 65bda9d22c2b3755e6fff855bdb54224359d8337
