### ISSUE TITLE
unknown package: libBF (dependency of crux)

### ISSUE THREAD

**Issue by schzene** [GaloisInc/crucible#956]
When I try to build https://github.com/GaloisInc/crucible/tree/master/uc-crux-llvm I get:

> \# cabal v2-build 
> Resolving dependencies...
> cabal: Could not resolve dependencies:
> [__0] trying: crux-0.5.0.99 (user goal)
> [__1] unknown package: libBF (dependency of crux)
> [__1] fail (backjumping, conflict set: crux, libBF)
> After searching the rest of the dependency tree exhaustively, these were the
> goals I've had most trouble fulfilling: crux, libBF

Platform: Ubuntu 18.04
Cabal version: 2.4.0.0
Other tool's version is in recommended version

**Comment by RyanGlScott** [comment]
This is a strange error, since `libBF` is available on Hackage [here](https://hackage.haskell.org/package/libBF). Have you tried running `cabal update` beforehand?

**Comment by schzene** [comment]
Yes, but it not work.

**Comment by RyanGlScott** [comment]
Can you post the results of running `cabal v2-build -v3`?

**Comment by schzene** [comment]
I changed the environment, the docker image is haskell:8.10-buster, and it works.
Thanks a lot!
