### ISSUE TITLE
Consider a more structured approach to conversions between representations

### ISSUE THREAD

**Issue by langston-barrett** [GaloisInc/crucible#96]
There are several notion of "type" in the crucible-llvm to SAW pipeline:
 1. `MemType`/`SymType`
 2. `MemModel.Type` (usually `G.Type`)
 3. `LLVM.AST.Type` (usually `L.Type`)
 4. `TypeRepr` (referred to as "Crucible type")

(Is this a complete list?)

Some of these have (partial) conversions between them:
```haskell
tcType :: L.Type -> TC SymType
tcMemType :: L.Type -> TC (Maybe MemType)
resolveMemType :: SymType -> TC (Maybe MemType)
MemType :: MemType -> SymType
asCrucibleType :: G.Type -> (forall tpr. TypeRepr tpr -> x) -> x
```

There are also several notions of "value":
 1. `LLVMConst`
 2. `LLVMVal`
 3. `LLVMExpr`
 4. `RegValue`
 5. `CFG.Expr`

With some conversions between them (these are somewhat more complex than the type conversions, because some of them require additional runtime information):
```haskell
unpackMemValue :: ([...]) => sym ->LLVMVal sym ->IO (AnyValue sym) -- RegValue
liftConstant :: ([...]) => LLVMConst -> LLVMGenerator h s arch ret (LLVMExpr s arch)
packMemValue :: ([...]) => sym -> G.Type -> TypeRepr tp -> RegValue sym tp -> IO (LLVMVal sym)
```
and I'm currently writing `LLVMConst -> LLVMVal`.

### Question: Can any of these "conversions" be systematized?

I found the above list by grepping through source code. Is there a way to codify these conversions? I think this might be helpful in the case of the types at least (where no additional runtime information is needed, and conversions are usually not in monads). 

For superset/subset relationships (such as `SymType`/`MemType`), an `Iso` from the `Lens` package might be a good way to do this, e.g.
```haskell
Iso' (Maybe SymType) MemType
Iso' (Maybe (forall tpr. TypeRepr tpr)) G.Type
```
For other overlapping-venn-diagram relationships (are there any of these?) something like [semi-iso](http://hackage.haskell.org/package/semi-iso) or [partial-isomorphisms](http://hackage.haskell.org/package/partial-isomorphisms) might do the trick.

**Comment by atomb** [comment]
We should think about this as part of the overall LLVM memory model refactoring.

**Comment by langston-barrett** [comment]
I don't know if this is really that realistic, will reopen if I have a flash of inspiration.
