### ISSUE TITLE
How to get detailed log message when using UC-CRUX-LLVM?

### ISSUE THREAD

**Issue by HuantWang** [GaloisInc/crucible#961]
when I run 
`uc-crux-llvm --entry-points double_free test/programs/double_free.c`
I found that there is only a simple log for errors. (looks like [UC-Crux-LLVM] Double free at test/programs/double_free.c:10:5)

Please tell me how to **obtain detailed information to know more about the execution process**, like:
_execution inputs/execution trace_, or anything during the execution process.

**Comment by HuantWang** [comment]
@langston-barrett Could you give me some ideas about that : )  Many thanks

**Comment by langston-barrett** [comment]
@HuantWang Try running with `--verbosity 2`. You should see a lot more output, including information about inputs and traces (example given below). Please let me know if there's anything that would be helpful to include in the either the default output or the verbose logs!
```
[Crux] Running double_free on arguments...
[Crux] Argument #0 ptr: symbolic integer:  width = 64
[Crux] Argument #1 x: symbolic integer:  width = 32
[Crux] Attempting to prove verification conditions.
Checking: 0 / 5[Crux] Explaining error: `free` called on pointer that was not previously returned by `malloc`
`calloc`, or another memory management function (the pointer did not
point to the base of an allocation, its offset should be 0)
[Crux] Error call stack:
[Crux] free_if_even
double_free
[Crux] Diagnosis:  `free` called on pointer with nonzero offset in argument #0 at <top>
[Crux] Prescription: Add a precondition that the pointer points to initialized memory.
Checking: 1 / 5[Crux] Explaining error: `free` called on pointer that didn't point to a live region of the heap
[Crux] Error call stack:
[Crux] free_if_even
double_free
[Crux] Diagnosis:  `free` called on an unallocated pointer in argument #0 at <top>
[Crux] Prescription: Add a precondition that the pointer points to initialized memory.
Checking: 2 / 5[Crux] Explaining error: `free` called on pointer that was not previously returned by `malloc`
`calloc`, or another memory management function (the pointer did not
point to the base of an allocation, its offset should be 0)
[Crux] Error call stack:
[Crux] free_if_multiple_of_three
double_free
[Crux] Diagnosis:  `free` called on pointer with nonzero offset in argument #0 at <top>
[Crux] Prescription: Add a precondition that the pointer points to initialized memory.
Checking: 3 / 5[Crux] Explaining error: `free` called on pointer that didn't point to a live region of the heap
[Crux] Error call stack:
[Crux] free_if_multiple_of_three
double_free
[Crux] Diagnosis:  `free` called on an unallocated pointer in argument #0 at <top>
[Crux] Prescription: Add a precondition that the pointer points to initialized memory.
Checking: 4 / 5[Crux] Explaining error: `free` called on a pointer to already-freed memory
[Crux] Error call stack:
[Crux] free_if_multiple_of_three
double_free
[Crux] Diagnosis:  `free` called on an unallocated pointer in argument #0 at <top>
[Crux] Prescription: Add a precondition that the pointer points to initialized memory.
[Crux] Trace:
[Crux]   test/programs/double_free.c:15:3
[Crux]   test/programs/double_free.c:3:13
[Crux]   test/programs/double_free.c:3:7
[Crux]   test/programs/double_free.c:4:5
[Crux]   test/programs/double_free.c:4:5
[Crux] Trace:
[Crux]   test/programs/double_free.c:15:3
[Crux]   test/programs/double_free.c:3:13
[Crux]   test/programs/double_free.c:3:7
[Crux]   test/programs/double_free.c:4:5
[Crux]   test/programs/double_free.c:6:1
[Crux]   test/programs/double_free.c:9:9
[Crux]   test/programs/double_free.c:9:7
[Crux]   test/programs/double_free.c:10:5
[Crux]   test/programs/double_free.c:10:5
[Crux] Trace:
[Crux]   test/programs/double_free.c:15:3
[Crux]   test/programs/double_free.c:3:13
[Crux]   test/programs/double_free.c:3:7
[Crux]   test/programs/double_free.c:6:1
[Crux]   test/programs/double_free.c:9:9
[Crux]   test/programs/double_free.c:9:7
[Crux]   test/programs/double_free.c:10:5
[Crux]   test/programs/double_free.c:10:5
[Crux] New preconditions:
[Crux] Arguments:
  A pointer to uninitialized space for 1 elements: 
  An integer: 
Globals:
Return values of skipped functions:
```
(More output follows...)

**Comment by HuantWang** [comment]
> @HuantWang Try running with `--verbosity 2`. You should see a lot more output, including information about inputs and traces (example given below). Please let me know if there's anything that would be helpful to include in the either the default output or the verbose logs!
> 
> ```
> [Crux] Running double_free on arguments...
> [Crux] Argument #0 ptr: symbolic integer:  width = 64
> [Crux] Argument #1 x: symbolic integer:  width = 32
> [Crux] Attempting to prove verification conditions.
> Checking: 0 / 5[Crux] Explaining error: `free` called on pointer that was not previously returned by `malloc`
> `calloc`, or another memory management function (the pointer did not
> point to the base of an allocation, its offset should be 0)
> [Crux] Error call stack:
> [Crux] free_if_even
> double_free
> [Crux] Diagnosis:  `free` called on pointer with nonzero offset in argument #0 at <top>
> [Crux] Prescription: Add a precondition that the pointer points to initialized memory.
> Checking: 1 / 5[Crux] Explaining error: `free` called on pointer that didn't point to a live region of the heap
> [Crux] Error call stack:
> [Crux] free_if_even
> double_free
> [Crux] Diagnosis:  `free` called on an unallocated pointer in argument #0 at <top>
> [Crux] Prescription: Add a precondition that the pointer points to initialized memory.
> Checking: 2 / 5[Crux] Explaining error: `free` called on pointer that was not previously returned by `malloc`
> `calloc`, or another memory management function (the pointer did not
> point to the base of an allocation, its offset should be 0)
> [Crux] Error call stack:
> [Crux] free_if_multiple_of_three
> double_free
> [Crux] Diagnosis:  `free` called on pointer with nonzero offset in argument #0 at <top>
> [Crux] Prescription: Add a precondition that the pointer points to initialized memory.
> Checking: 3 / 5[Crux] Explaining error: `free` called on pointer that didn't point to a live region of the heap
> [Crux] Error call stack:
> [Crux] free_if_multiple_of_three
> double_free
> [Crux] Diagnosis:  `free` called on an unallocated pointer in argument #0 at <top>
> [Crux] Prescription: Add a precondition that the pointer points to initialized memory.
> Checking: 4 / 5[Crux] Explaining error: `free` called on a pointer to already-freed memory
> [Crux] Error call stack:
> [Crux] free_if_multiple_of_three
> double_free
> [Crux] Diagnosis:  `free` called on an unallocated pointer in argument #0 at <top>
> [Crux] Prescription: Add a precondition that the pointer points to initialized memory.
> [Crux] Trace:
> [Crux]   test/programs/double_free.c:15:3
> [Crux]   test/programs/double_free.c:3:13
> [Crux]   test/programs/double_free.c:3:7
> [Crux]   test/programs/double_free.c:4:5
> [Crux]   test/programs/double_free.c:4:5
> [Crux] Trace:
> [Crux]   test/programs/double_free.c:15:3
> [Crux]   test/programs/double_free.c:3:13
> [Crux]   test/programs/double_free.c:3:7
> [Crux]   test/programs/double_free.c:4:5
> [Crux]   test/programs/double_free.c:6:1
> [Crux]   test/programs/double_free.c:9:9
> [Crux]   test/programs/double_free.c:9:7
> [Crux]   test/programs/double_free.c:10:5
> [Crux]   test/programs/double_free.c:10:5
> [Crux] Trace:
> [Crux]   test/programs/double_free.c:15:3
> [Crux]   test/programs/double_free.c:3:13
> [Crux]   test/programs/double_free.c:3:7
> [Crux]   test/programs/double_free.c:6:1
> [Crux]   test/programs/double_free.c:9:9
> [Crux]   test/programs/double_free.c:9:7
> [Crux]   test/programs/double_free.c:10:5
> [Crux]   test/programs/double_free.c:10:5
> [Crux] New preconditions:
> [Crux] Arguments:
>   A pointer to uninitialized space for 1 elements: 
>   An integer: 
> Globals:
> Return values of skipped functions:
> ```
> 
> (More output follows...)

Thanks! @langston-barrett 
Could give me some suggestions about extending UC-CRUX to get more debug information. For example, If I intend to observe input test cases generated by CRUX-LLVM and correspond execution trace (now it's only shown when detecting vulnerabilities). 

Which functions should I notice or what tools are helpful to debug CRUX source code? (I'm a beginner at Haskell but full of interest.)  Many thanks.

**Comment by langston-barrett** [comment]
> For example, If I intend to observe input test cases generated by CRUX-LLVM and correspond execution trace (now it's only shown when detecting vulnerabilities).

The inputs generated by UC-Crux are symbolic, so they can't easily be displayed. This part of the log shows their general shape:
```
[Crux] Running double_free on arguments...
[Crux] Argument #0 ptr: symbolic integer:  width = 64
[Crux] Argument #1 x: symbolic integer:  width = 32
```
As for the corresponding execution trace, if UC-Crux doesn't report a potential bug it means that it explored *all* paths through the program and didn't find one, so there is no single execution trace. As for printing all possible traces... These traces come from [Crux's `ProvedGoals` type](https://github.com/GaloisInc/crucible/blob/59bc02fee7749dc286206f811bf3f7aa3ee1b487/crux/src/Crux/Types.hs#L67), so if you can find where that's populated you might be able to preserve them, but I don't think that will be a simple beginner Haskell project. Here's where the traces are printed, for what that's worth: https://github.com/GaloisInc/crucible/blob/59bc02fee7749dc286206f811bf3f7aa3ee1b487/uc-crux-llvm/src/UCCrux/LLVM/Run/Simulate.hs#L560

Feel free to post some more details about how you're using UC-Crux, and I will try to see if there's any changes I could make to support your use-case!
